package dev.alaindustrial.core.environment;

/**
 * GENERATED by tools/gen_mob_wheel_assets.py — do not edit.
 *
 * <p>Where the occupant of the mob wheel (MOD-763) may stand, in pixels of the CANONICAL structure
 * (0..48 on every axis; wheel axis Z, gate side +Z, controller in cell (2, 0, 0) — the frame of
 * {@code MobWheelGeometry}). Minecraft-free on purpose, so the behaviour code and L1 tests can read it.
 *
 * <p>Every rotor cube turns about the axle, so over a full turn it sweeps the ring between its nearest
 * and farthest distance from it; {@link #ROTOR_INNER_RADIUS_PX} is the nearest of the cubes that reach
 * the interior. {@link #ROTOR_FLOOR_PX} is the highest point of that ring under the footprint of the
 * widest supported runner (centred on the axle), so a mob whose feet are there never sinks into a
 * plank at any wheel angle; {@link #ROTOR_CEILING_PX} is the lowest point above it. The generator
 * also checks every supported runner, centred and standing on the floor, against every rotor cube at
 * every whole degree of a turn. Runners (blocks, width x height):
 * chicken 0.4x0.7, pig 0.9x0.9, sheep 0.9x1.3, goat 0.9x1.3, cow 0.9x1.4, creeper 0.6x1.7, villager
 * 0.6x1.95, zombie 0.6x1.95, skeleton 0.6x1.99.
 */
public final class MobWheelLayout {
	/** Centre of the wheel (its axle runs along Z through it), canonical pixels. */
	public static final double[] ROTOR_CENTER_PX = {24.0, 24.0, 24.0};
	/** Top of the running planks at the bottom of the wheel, highest over a full turn, canonical pixels. */
	public static final double ROTOR_FLOOR_PX = 7.722;
	/** Bottom of the planks at the top of the wheel, lowest over a full turn, canonical pixels. */
	public static final double ROTOR_CEILING_PX = 40.278;
	/** Distance from the axle to the inner face of a running plank, pixels. */
	public static final double ROTOR_INNER_RADIUS_PX = 17.8;
	/** Width of the footprint the floor and ceiling were measured under (the widest runner), pixels. */
	public static final double FOOTPRINT_WIDTH_PX = 14.4;
	/** Lower corner of the box a runner may occupy without clipping the wheel, canonical pixels. */
	public static final double[] INTERIOR_MIN_PX = {16.8, 7.722, 14.5};
	/** Upper corner of that box, canonical pixels. */
	public static final double[] INTERIOR_MAX_PX = {31.2, 40.278, 36.0};

	private MobWheelLayout() {
	}
}
