package dev.alaindustrial.gametest;

import java.util.List;

/**
 * Reviewed energy role per face (order DUNSWE; I in, O out, B both, N none) of every powered block
 * entity (MOD-712) — the reference {@link EnergyRoleForFaceSnapshotScenarios} compares against.
 *
 * <p>Written by that scenario, and only on the explicit command below (ADR-032); never by
 * {@code regen.py}, a hook or a merge driver. The same file serves both gametest lanes.
 *
 * <p>Update command (absolute directory; Fabric lane):
 * <pre>
 * JAVA_TOOL_OPTIONS="-Dfabric-api.gametest.filter=*:machine_char_energy_role*
 *   -Dalaindustrial.referenceLines.writeDir=&lt;repo&gt;/common/src/gametest/java/dev/alaindustrial/gametest"
 *   ./gradlew :fabric:runGameTest
 * </pre>
 * The run fails on purpose after writing; review the diff, then commit it together
 * with the change that is meant to move it.
 */
final class EnergyRoleForFaceSnapshot {

	private EnergyRoleForFaceSnapshot() {}

	static final List<String> LINES = List.of(
			"generator[facing=north,lit=true] DUNSWE=OONOOO",
			"generator[facing=north,lit=false] DUNSWE=OONOOO",
			"generator[facing=south,lit=true] DUNSWE=OOONOO",
			"generator[facing=south,lit=false] DUNSWE=OOONOO",
			"generator[facing=west,lit=true] DUNSWE=OOOONO",
			"generator[facing=west,lit=false] DUNSWE=OOOONO",
			"generator[facing=east,lit=true] DUNSWE=OOOOON",
			"generator[facing=east,lit=false] DUNSWE=OOOOON",
			"geothermal_generator[facing=north,lit=true] DUNSWE=OONOOO",
			"geothermal_generator[facing=north,lit=false] DUNSWE=OONOOO",
			"geothermal_generator[facing=south,lit=true] DUNSWE=OOONOO",
			"geothermal_generator[facing=south,lit=false] DUNSWE=OOONOO",
			"geothermal_generator[facing=west,lit=true] DUNSWE=OOOONO",
			"geothermal_generator[facing=west,lit=false] DUNSWE=OOOONO",
			"geothermal_generator[facing=east,lit=true] DUNSWE=OOOOON",
			"geothermal_generator[facing=east,lit=false] DUNSWE=OOOOON",
			"solar_panel[] DUNSWE=ONOOOO",
			"moonlit_solar_panel[] DUNSWE=ONOOOO",
			"daylight_solar_panel[] DUNSWE=ONOOOO",
			"radiant_solar_panel[assembled=true,facing=north] DUNSWE=ONOOOO",
			"radiant_solar_panel[assembled=true,facing=south] DUNSWE=ONOOOO",
			"radiant_solar_panel[assembled=true,facing=west] DUNSWE=ONOOOO",
			"radiant_solar_panel[assembled=true,facing=east] DUNSWE=ONOOOO",
			"radiant_solar_panel[assembled=false,facing=north] DUNSWE=ONOOOO",
			"radiant_solar_panel[assembled=false,facing=south] DUNSWE=ONOOOO",
			"radiant_solar_panel[assembled=false,facing=west] DUNSWE=ONOOOO",
			"radiant_solar_panel[assembled=false,facing=east] DUNSWE=ONOOOO",
			"water_mill[facing=north] DUNSWE=NNNONN",
			"water_mill[facing=south] DUNSWE=NNONNN",
			"water_mill[facing=west] DUNSWE=NNNNNO",
			"water_mill[facing=east] DUNSWE=NNNNON",
			"wind_mill[facing=north] DUNSWE=NNNONN",
			"wind_mill[facing=south] DUNSWE=NNONNN",
			"wind_mill[facing=west] DUNSWE=NNNNNO",
			"wind_mill[facing=east] DUNSWE=NNNNON",
			"high_altitude_wind_mill[facing=north] DUNSWE=NNNONN",
			"high_altitude_wind_mill[facing=south] DUNSWE=NNONNN",
			"high_altitude_wind_mill[facing=west] DUNSWE=NNNNNO",
			"high_altitude_wind_mill[facing=east] DUNSWE=NNNNON",
			"storm_wind_mill[facing=north] DUNSWE=NNNONN",
			"storm_wind_mill[facing=south] DUNSWE=NNONNN",
			"storm_wind_mill[facing=west] DUNSWE=NNNNNO",
			"storm_wind_mill[facing=east] DUNSWE=NNNNON",
			"lightning_rod_generator[lit=true,tipped=true] DUNSWE=ONOOOO",
			"lightning_rod_generator[lit=true,tipped=false] DUNSWE=ONOOOO",
			"lightning_rod_generator[lit=false,tipped=true] DUNSWE=ONOOOO",
			"lightning_rod_generator[lit=false,tipped=false] DUNSWE=ONOOOO",
			"creative_energy_source[lit=true] DUNSWE=OOOOOO",
			"creative_energy_source[lit=false] DUNSWE=OOOOOO",
			"mob_wheel_controller[facing=north,formed=true] DUNSWE=NNNOON",
			"mob_wheel_controller[facing=north,formed=false] DUNSWE=NNNOON",
			"mob_wheel_controller[facing=south,formed=true] DUNSWE=NNONNO",
			"mob_wheel_controller[facing=south,formed=false] DUNSWE=NNONNO",
			"mob_wheel_controller[facing=west,formed=true] DUNSWE=NNNONO",
			"mob_wheel_controller[facing=west,formed=false] DUNSWE=NNNONO",
			"mob_wheel_controller[facing=east,formed=true] DUNSWE=NNONON",
			"mob_wheel_controller[facing=east,formed=false] DUNSWE=NNONON",
			"piezo_plate[powered=true] DUNSWE=ONOOOO",
			"piezo_plate[powered=false] DUNSWE=ONOOOO",
			"piezo_plate@silent_piezo_plate[powered=true] DUNSWE=ONOOOO",
			"piezo_plate@silent_piezo_plate[powered=false] DUNSWE=ONOOOO",
			"copper_cable[breaker_open=false,down=false,east=false,east_low=false,north=false,north_low"
					+ "=false,south=false,south_low=false,up=false,west=false,west_low=false] DUNSWE=BBBBBB",
			"copper_cable@tin_cable[breaker_open=false,down=false,east=false,east_low=false,north=false"
					+ ",north_low=false,south=false,south_low=false,up=false,west=false,west_low=false]"
					+ " DUNSWE=BBBBBB",
			"copper_cable@gold_cable[breaker_open=false,down=false,east=false,east_low=false,north=fals"
					+ "e,north_low=false,south=false,south_low=false,up=false,west=false,west_low=false]"
					+ " DUNSWE=BBBBBB",
			"copper_cable@electrum_cable[breaker_open=false,down=false,east=false,east_low=false,north="
					+ "false,north_low=false,south=false,south_low=false,up=false,west=false,west_low=false]"
					+ " DUNSWE=BBBBBB",
			"copper_cable@insulated_copper_cable[breaker_open=false,down=false,east=false,east_low=fals"
					+ "e,north=false,north_low=false,south=false,south_low=false,up=false,west=false,west_low=fal"
					+ "se] DUNSWE=BBBBBB",
			"copper_cable@insulated_tin_cable[breaker_open=false,down=false,east=false,east_low=false,n"
					+ "orth=false,north_low=false,south=false,south_low=false,up=false,west=false,west_low=false]"
					+ " DUNSWE=BBBBBB",
			"copper_cable@insulated_gold_cable[breaker_open=false,down=false,east=false,east_low=false,"
					+ "north=false,north_low=false,south=false,south_low=false,up=false,west=false,west_low=false"
					+ "] DUNSWE=BBBBBB",
			"copper_cable@insulated_electrum_cable[breaker_open=false,down=false,east=false,east_low=fa"
					+ "lse,north=false,north_low=false,south=false,south_low=false,up=false,west=false,west_low=f"
					+ "alse] DUNSWE=BBBBBB",
			"macerator[facing=north,lit=true] DUNSWE=IINIII",
			"macerator[facing=north,lit=false] DUNSWE=IINIII",
			"macerator[facing=south,lit=true] DUNSWE=IIINII",
			"macerator[facing=south,lit=false] DUNSWE=IIINII",
			"macerator[facing=west,lit=true] DUNSWE=IIIINI",
			"macerator[facing=west,lit=false] DUNSWE=IIIINI",
			"macerator[facing=east,lit=true] DUNSWE=IIIIIN",
			"macerator[facing=east,lit=false] DUNSWE=IIIIIN",
			"component_repair_bench[facing=north,lit=true] DUNSWE=IINIII",
			"component_repair_bench[facing=north,lit=false] DUNSWE=IINIII",
			"component_repair_bench[facing=south,lit=true] DUNSWE=IIINII",
			"component_repair_bench[facing=south,lit=false] DUNSWE=IIINII",
			"component_repair_bench[facing=west,lit=true] DUNSWE=IIIINI",
			"component_repair_bench[facing=west,lit=false] DUNSWE=IIIINI",
			"component_repair_bench[facing=east,lit=true] DUNSWE=IIIIIN",
			"component_repair_bench[facing=east,lit=false] DUNSWE=IIIIIN",
			"upgrade_table[facing=north,lit=true,part=single] DUNSWE=NNNNNN",
			"upgrade_table[facing=north,lit=true,part=lower] DUNSWE=IINIII",
			"upgrade_table[facing=north,lit=true,part=upper] DUNSWE=NNNNNN",
			"upgrade_table[facing=north,lit=false,part=single] DUNSWE=NNNNNN",
			"upgrade_table[facing=north,lit=false,part=lower] DUNSWE=IINIII",
			"upgrade_table[facing=north,lit=false,part=upper] DUNSWE=NNNNNN",
			"upgrade_table[facing=south,lit=true,part=single] DUNSWE=NNNNNN",
			"upgrade_table[facing=south,lit=true,part=lower] DUNSWE=IIINII",
			"upgrade_table[facing=south,lit=true,part=upper] DUNSWE=NNNNNN",
			"upgrade_table[facing=south,lit=false,part=single] DUNSWE=NNNNNN",
			"upgrade_table[facing=south,lit=false,part=lower] DUNSWE=IIINII",
			"upgrade_table[facing=south,lit=false,part=upper] DUNSWE=NNNNNN",
			"upgrade_table[facing=west,lit=true,part=single] DUNSWE=NNNNNN",
			"upgrade_table[facing=west,lit=true,part=lower] DUNSWE=IIIINI",
			"upgrade_table[facing=west,lit=true,part=upper] DUNSWE=NNNNNN",
			"upgrade_table[facing=west,lit=false,part=single] DUNSWE=NNNNNN",
			"upgrade_table[facing=west,lit=false,part=lower] DUNSWE=IIIINI",
			"upgrade_table[facing=west,lit=false,part=upper] DUNSWE=NNNNNN",
			"upgrade_table[facing=east,lit=true,part=single] DUNSWE=NNNNNN",
			"upgrade_table[facing=east,lit=true,part=lower] DUNSWE=IIIIIN",
			"upgrade_table[facing=east,lit=true,part=upper] DUNSWE=NNNNNN",
			"upgrade_table[facing=east,lit=false,part=single] DUNSWE=NNNNNN",
			"upgrade_table[facing=east,lit=false,part=lower] DUNSWE=IIIIIN",
			"upgrade_table[facing=east,lit=false,part=upper] DUNSWE=NNNNNN",
			"teleporter[facing=north,formed=true,upgraded=true] DUNSWE=IINIII",
			"teleporter[facing=north,formed=true,upgraded=false] DUNSWE=IINIII",
			"teleporter[facing=north,formed=false,upgraded=true] DUNSWE=IINIII",
			"teleporter[facing=north,formed=false,upgraded=false] DUNSWE=IINIII",
			"teleporter[facing=south,formed=true,upgraded=true] DUNSWE=IIINII",
			"teleporter[facing=south,formed=true,upgraded=false] DUNSWE=IIINII",
			"teleporter[facing=south,formed=false,upgraded=true] DUNSWE=IIINII",
			"teleporter[facing=south,formed=false,upgraded=false] DUNSWE=IIINII",
			"teleporter[facing=west,formed=true,upgraded=true] DUNSWE=IIIINI",
			"teleporter[facing=west,formed=true,upgraded=false] DUNSWE=IIIINI",
			"teleporter[facing=west,formed=false,upgraded=true] DUNSWE=IIIINI",
			"teleporter[facing=west,formed=false,upgraded=false] DUNSWE=IIIINI",
			"teleporter[facing=east,formed=true,upgraded=true] DUNSWE=IIIIIN",
			"teleporter[facing=east,formed=true,upgraded=false] DUNSWE=IIIIIN",
			"teleporter[facing=east,formed=false,upgraded=true] DUNSWE=IIIIIN",
			"teleporter[facing=east,formed=false,upgraded=false] DUNSWE=IIIIIN",
			"electric_furnace[facing=north,lit=true] DUNSWE=IINIII",
			"electric_furnace[facing=north,lit=false] DUNSWE=IINIII",
			"electric_furnace[facing=south,lit=true] DUNSWE=IIINII",
			"electric_furnace[facing=south,lit=false] DUNSWE=IIINII",
			"electric_furnace[facing=west,lit=true] DUNSWE=IIIINI",
			"electric_furnace[facing=west,lit=false] DUNSWE=IIIINI",
			"electric_furnace[facing=east,lit=true] DUNSWE=IIIIIN",
			"electric_furnace[facing=east,lit=false] DUNSWE=IIIIIN",
			"extractor[facing=north,lit=true] DUNSWE=IINIII",
			"extractor[facing=north,lit=false] DUNSWE=IINIII",
			"extractor[facing=south,lit=true] DUNSWE=IIINII",
			"extractor[facing=south,lit=false] DUNSWE=IIINII",
			"extractor[facing=west,lit=true] DUNSWE=IIIINI",
			"extractor[facing=west,lit=false] DUNSWE=IIIINI",
			"extractor[facing=east,lit=true] DUNSWE=IIIIIN",
			"extractor[facing=east,lit=false] DUNSWE=IIIIIN",
			"compressor[facing=north,lit=true] DUNSWE=IINIII",
			"compressor[facing=north,lit=false] DUNSWE=IINIII",
			"compressor[facing=south,lit=true] DUNSWE=IIINII",
			"compressor[facing=south,lit=false] DUNSWE=IIINII",
			"compressor[facing=west,lit=true] DUNSWE=IIIINI",
			"compressor[facing=west,lit=false] DUNSWE=IIIINI",
			"compressor[facing=east,lit=true] DUNSWE=IIIIIN",
			"compressor[facing=east,lit=false] DUNSWE=IIIIIN",
			"recycler[facing=north,lamps=0,lit=true] DUNSWE=IINIII",
			"recycler[facing=north,lamps=0,lit=false] DUNSWE=IINIII",
			"recycler[facing=north,lamps=1,lit=true] DUNSWE=IINIII",
			"recycler[facing=north,lamps=1,lit=false] DUNSWE=IINIII",
			"recycler[facing=north,lamps=2,lit=true] DUNSWE=IINIII",
			"recycler[facing=north,lamps=2,lit=false] DUNSWE=IINIII",
			"recycler[facing=north,lamps=3,lit=true] DUNSWE=IINIII",
			"recycler[facing=north,lamps=3,lit=false] DUNSWE=IINIII",
			"recycler[facing=south,lamps=0,lit=true] DUNSWE=IIINII",
			"recycler[facing=south,lamps=0,lit=false] DUNSWE=IIINII",
			"recycler[facing=south,lamps=1,lit=true] DUNSWE=IIINII",
			"recycler[facing=south,lamps=1,lit=false] DUNSWE=IIINII",
			"recycler[facing=south,lamps=2,lit=true] DUNSWE=IIINII",
			"recycler[facing=south,lamps=2,lit=false] DUNSWE=IIINII",
			"recycler[facing=south,lamps=3,lit=true] DUNSWE=IIINII",
			"recycler[facing=south,lamps=3,lit=false] DUNSWE=IIINII",
			"recycler[facing=west,lamps=0,lit=true] DUNSWE=IIIINI",
			"recycler[facing=west,lamps=0,lit=false] DUNSWE=IIIINI",
			"recycler[facing=west,lamps=1,lit=true] DUNSWE=IIIINI",
			"recycler[facing=west,lamps=1,lit=false] DUNSWE=IIIINI",
			"recycler[facing=west,lamps=2,lit=true] DUNSWE=IIIINI",
			"recycler[facing=west,lamps=2,lit=false] DUNSWE=IIIINI",
			"recycler[facing=west,lamps=3,lit=true] DUNSWE=IIIINI",
			"recycler[facing=west,lamps=3,lit=false] DUNSWE=IIIINI",
			"recycler[facing=east,lamps=0,lit=true] DUNSWE=IIIIIN",
			"recycler[facing=east,lamps=0,lit=false] DUNSWE=IIIIIN",
			"recycler[facing=east,lamps=1,lit=true] DUNSWE=IIIIIN",
			"recycler[facing=east,lamps=1,lit=false] DUNSWE=IIIIIN",
			"recycler[facing=east,lamps=2,lit=true] DUNSWE=IIIIIN",
			"recycler[facing=east,lamps=2,lit=false] DUNSWE=IIIIIN",
			"recycler[facing=east,lamps=3,lit=true] DUNSWE=IIIIIN",
			"recycler[facing=east,lamps=3,lit=false] DUNSWE=IIIIIN",
			"canning_machine[facing=north,lit=true] DUNSWE=IINIII",
			"canning_machine[facing=north,lit=false] DUNSWE=IINIII",
			"canning_machine[facing=south,lit=true] DUNSWE=IIINII",
			"canning_machine[facing=south,lit=false] DUNSWE=IIINII",
			"canning_machine[facing=west,lit=true] DUNSWE=IIIINI",
			"canning_machine[facing=west,lit=false] DUNSWE=IIIINI",
			"canning_machine[facing=east,lit=true] DUNSWE=IIIIIN",
			"canning_machine[facing=east,lit=false] DUNSWE=IIIIIN",
			"sawmill[facing=north,lit=true] DUNSWE=IINIII",
			"sawmill[facing=north,lit=false] DUNSWE=IINIII",
			"sawmill[facing=south,lit=true] DUNSWE=IIINII",
			"sawmill[facing=south,lit=false] DUNSWE=IIINII",
			"sawmill[facing=west,lit=true] DUNSWE=IIIINI",
			"sawmill[facing=west,lit=false] DUNSWE=IIIINI",
			"sawmill[facing=east,lit=true] DUNSWE=IIIIIN",
			"sawmill[facing=east,lit=false] DUNSWE=IIIIIN",
			"assembler[facing=north] DUNSWE=IINIII",
			"assembler[facing=south] DUNSWE=IIINII",
			"assembler[facing=west] DUNSWE=IIIINI",
			"assembler[facing=east] DUNSWE=IIIIIN",
			"polymerizer[facing=north,lit=true] DUNSWE=IINIII",
			"polymerizer[facing=north,lit=false] DUNSWE=IINIII",
			"polymerizer[facing=south,lit=true] DUNSWE=IIINII",
			"polymerizer[facing=south,lit=false] DUNSWE=IIINII",
			"polymerizer[facing=west,lit=true] DUNSWE=IIIINI",
			"polymerizer[facing=west,lit=false] DUNSWE=IIIINI",
			"polymerizer[facing=east,lit=true] DUNSWE=IIIIIN",
			"polymerizer[facing=east,lit=false] DUNSWE=IIIIIN",
			"vulcanizer[facing=north,lit=true] DUNSWE=IINIII",
			"vulcanizer[facing=north,lit=false] DUNSWE=IINIII",
			"vulcanizer[facing=south,lit=true] DUNSWE=IIINII",
			"vulcanizer[facing=south,lit=false] DUNSWE=IIINII",
			"vulcanizer[facing=west,lit=true] DUNSWE=IIIINI",
			"vulcanizer[facing=west,lit=false] DUNSWE=IIIINI",
			"vulcanizer[facing=east,lit=true] DUNSWE=IIIIIN",
			"vulcanizer[facing=east,lit=false] DUNSWE=IIIIIN",
			"alloy_smelter[facing=north,lit=true] DUNSWE=IINIII",
			"alloy_smelter[facing=north,lit=false] DUNSWE=IINIII",
			"alloy_smelter[facing=south,lit=true] DUNSWE=IIINII",
			"alloy_smelter[facing=south,lit=false] DUNSWE=IIINII",
			"alloy_smelter[facing=west,lit=true] DUNSWE=IIIINI",
			"alloy_smelter[facing=west,lit=false] DUNSWE=IIIINI",
			"alloy_smelter[facing=east,lit=true] DUNSWE=IIIIIN",
			"alloy_smelter[facing=east,lit=false] DUNSWE=IIIIIN",
			"galvanic_bath[facing=north,lit=true] DUNSWE=IINIII",
			"galvanic_bath[facing=north,lit=false] DUNSWE=IINIII",
			"galvanic_bath[facing=south,lit=true] DUNSWE=IIINII",
			"galvanic_bath[facing=south,lit=false] DUNSWE=IIINII",
			"galvanic_bath[facing=west,lit=true] DUNSWE=IIIINI",
			"galvanic_bath[facing=west,lit=false] DUNSWE=IIIINI",
			"galvanic_bath[facing=east,lit=true] DUNSWE=IIIIIN",
			"galvanic_bath[facing=east,lit=false] DUNSWE=IIIIIN",
			"electric_heater[drawing=true,facing=north,glow=cold] DUNSWE=IINIII",
			"electric_heater[drawing=true,facing=north,glow=warm] DUNSWE=IINIII",
			"electric_heater[drawing=true,facing=north,glow=hot] DUNSWE=IINIII",
			"electric_heater[drawing=true,facing=north,glow=glowing] DUNSWE=IINIII",
			"electric_heater[drawing=true,facing=south,glow=cold] DUNSWE=IIINII",
			"electric_heater[drawing=true,facing=south,glow=warm] DUNSWE=IIINII",
			"electric_heater[drawing=true,facing=south,glow=hot] DUNSWE=IIINII",
			"electric_heater[drawing=true,facing=south,glow=glowing] DUNSWE=IIINII",
			"electric_heater[drawing=true,facing=west,glow=cold] DUNSWE=IIIINI",
			"electric_heater[drawing=true,facing=west,glow=warm] DUNSWE=IIIINI",
			"electric_heater[drawing=true,facing=west,glow=hot] DUNSWE=IIIINI",
			"electric_heater[drawing=true,facing=west,glow=glowing] DUNSWE=IIIINI",
			"electric_heater[drawing=true,facing=east,glow=cold] DUNSWE=IIIIIN",
			"electric_heater[drawing=true,facing=east,glow=warm] DUNSWE=IIIIIN",
			"electric_heater[drawing=true,facing=east,glow=hot] DUNSWE=IIIIIN",
			"electric_heater[drawing=true,facing=east,glow=glowing] DUNSWE=IIIIIN",
			"electric_heater[drawing=false,facing=north,glow=cold] DUNSWE=IINIII",
			"electric_heater[drawing=false,facing=north,glow=warm] DUNSWE=IINIII",
			"electric_heater[drawing=false,facing=north,glow=hot] DUNSWE=IINIII",
			"electric_heater[drawing=false,facing=north,glow=glowing] DUNSWE=IINIII",
			"electric_heater[drawing=false,facing=south,glow=cold] DUNSWE=IIINII",
			"electric_heater[drawing=false,facing=south,glow=warm] DUNSWE=IIINII",
			"electric_heater[drawing=false,facing=south,glow=hot] DUNSWE=IIINII",
			"electric_heater[drawing=false,facing=south,glow=glowing] DUNSWE=IIINII",
			"electric_heater[drawing=false,facing=west,glow=cold] DUNSWE=IIIINI",
			"electric_heater[drawing=false,facing=west,glow=warm] DUNSWE=IIIINI",
			"electric_heater[drawing=false,facing=west,glow=hot] DUNSWE=IIIINI",
			"electric_heater[drawing=false,facing=west,glow=glowing] DUNSWE=IIIINI",
			"electric_heater[drawing=false,facing=east,glow=cold] DUNSWE=IIIIIN",
			"electric_heater[drawing=false,facing=east,glow=warm] DUNSWE=IIIIIN",
			"electric_heater[drawing=false,facing=east,glow=hot] DUNSWE=IIIIIN",
			"electric_heater[drawing=false,facing=east,glow=glowing] DUNSWE=IIIIIN",
			"thermal_centrifuge[facing=north,lit=true] DUNSWE=IINIII",
			"thermal_centrifuge[facing=north,lit=false] DUNSWE=IINIII",
			"thermal_centrifuge[facing=south,lit=true] DUNSWE=IIINII",
			"thermal_centrifuge[facing=south,lit=false] DUNSWE=IIINII",
			"thermal_centrifuge[facing=west,lit=true] DUNSWE=IIIINI",
			"thermal_centrifuge[facing=west,lit=false] DUNSWE=IIIINI",
			"thermal_centrifuge[facing=east,lit=true] DUNSWE=IIIIIN",
			"thermal_centrifuge[facing=east,lit=false] DUNSWE=IIIIIN",
			"workstation[facing=north,lit=true,part=single] DUNSWE=NNNNNN",
			"workstation[facing=north,lit=true,part=lower] DUNSWE=IINIII",
			"workstation[facing=north,lit=true,part=upper] DUNSWE=NNNNNN",
			"workstation[facing=north,lit=false,part=single] DUNSWE=NNNNNN",
			"workstation[facing=north,lit=false,part=lower] DUNSWE=IINIII",
			"workstation[facing=north,lit=false,part=upper] DUNSWE=NNNNNN",
			"workstation[facing=south,lit=true,part=single] DUNSWE=NNNNNN",
			"workstation[facing=south,lit=true,part=lower] DUNSWE=IIINII",
			"workstation[facing=south,lit=true,part=upper] DUNSWE=NNNNNN",
			"workstation[facing=south,lit=false,part=single] DUNSWE=NNNNNN",
			"workstation[facing=south,lit=false,part=lower] DUNSWE=IIINII",
			"workstation[facing=south,lit=false,part=upper] DUNSWE=NNNNNN",
			"workstation[facing=west,lit=true,part=single] DUNSWE=NNNNNN",
			"workstation[facing=west,lit=true,part=lower] DUNSWE=IIIINI",
			"workstation[facing=west,lit=true,part=upper] DUNSWE=NNNNNN",
			"workstation[facing=west,lit=false,part=single] DUNSWE=NNNNNN",
			"workstation[facing=west,lit=false,part=lower] DUNSWE=IIIINI",
			"workstation[facing=west,lit=false,part=upper] DUNSWE=NNNNNN",
			"workstation[facing=east,lit=true,part=single] DUNSWE=NNNNNN",
			"workstation[facing=east,lit=true,part=lower] DUNSWE=IIIIIN",
			"workstation[facing=east,lit=true,part=upper] DUNSWE=NNNNNN",
			"workstation[facing=east,lit=false,part=single] DUNSWE=NNNNNN",
			"workstation[facing=east,lit=false,part=lower] DUNSWE=IIIIIN",
			"workstation[facing=east,lit=false,part=upper] DUNSWE=NNNNNN",
			"fluid_pipe[down_mode=disabled,east_mode=disabled,filled=false,north_mode=disabled,south_mo"
					+ "de=disabled,up_mode=disabled,west_mode=disabled] DUNSWE=NNNNNN",
			"fluid_pipe@fluid_pipe_advanced[down_mode=disabled,east_mode=disabled,filled=false,north_mo"
					+ "de=disabled,south_mode=disabled,up_mode=disabled,west_mode=disabled] DUNSWE=NNNNNN",
			"fluid_pipe@reinforced_fluid_pipe[down_mode=disabled,east_mode=disabled,filled=false,north_"
					+ "mode=disabled,south_mode=disabled,up_mode=disabled,west_mode=disabled] DUNSWE=NNNNNN",
			"fluid_pipe@steam_pipe[down_mode=disabled,east_mode=disabled,filled=false,north_mode=disabl"
					+ "ed,south_mode=disabled,up_mode=disabled,west_mode=disabled] DUNSWE=NNNNNN",
			"fluid_pipe@reinforced_steam_pipe[down_mode=disabled,east_mode=disabled,filled=false,north_"
					+ "mode=disabled,south_mode=disabled,up_mode=disabled,west_mode=disabled] DUNSWE=NNNNNN",
			"distillation_column[formed=true,lit=true] DUNSWE=IIIIII",
			"distillation_column[formed=true,lit=false] DUNSWE=IIIIII",
			"distillation_column[formed=false,lit=true] DUNSWE=NNNNNN",
			"distillation_column[formed=false,lit=false] DUNSWE=NNNNNN",
			"pump[facing=north,lit=true] DUNSWE=IINIII",
			"pump[facing=north,lit=false] DUNSWE=IINIII",
			"pump[facing=south,lit=true] DUNSWE=IIINII",
			"pump[facing=south,lit=false] DUNSWE=IIINII",
			"pump[facing=west,lit=true] DUNSWE=IIIINI",
			"pump[facing=west,lit=false] DUNSWE=IIIINI",
			"pump[facing=east,lit=true] DUNSWE=IIIIIN",
			"pump[facing=east,lit=false] DUNSWE=IIIIIN",
			"fermenter[facing=north,lit=true] DUNSWE=IINIII",
			"fermenter[facing=north,lit=false] DUNSWE=IINIII",
			"fermenter[facing=south,lit=true] DUNSWE=IIINII",
			"fermenter[facing=south,lit=false] DUNSWE=IIINII",
			"fermenter[facing=west,lit=true] DUNSWE=IIIINI",
			"fermenter[facing=west,lit=false] DUNSWE=IIIINI",
			"fermenter[facing=east,lit=true] DUNSWE=IIIIIN",
			"fermenter[facing=east,lit=false] DUNSWE=IIIIIN",
			"item_pipe[down_mode=disabled,east_mode=disabled,north_mode=disabled,south_mode=disabled,up"
					+ "_mode=disabled,west_mode=disabled] DUNSWE=NNNNNN",
			"item_pipe@item_pipe_advanced[down_mode=disabled,east_mode=disabled,north_mode=disabled,sou"
					+ "th_mode=disabled,up_mode=disabled,west_mode=disabled] DUNSWE=NNNNNN",
			"monitor_core[cards=0,facing=north,lit=false] DUNSWE=IINIII",
			"monitor_core[cards=0,facing=south,lit=false] DUNSWE=IIINII",
			"monitor_core[cards=0,facing=west,lit=false] DUNSWE=IIIINI",
			"monitor_core[cards=0,facing=east,lit=false] DUNSWE=IIIIIN",
			"battery_box[facing=north] DUNSWE=NNIONN",
			"battery_box[facing=south] DUNSWE=NNOINN",
			"battery_box[facing=west] DUNSWE=NNNNIO",
			"battery_box[facing=east] DUNSWE=NNNNOI",
			"cesu[facing=north] DUNSWE=NNIONN",
			"cesu[facing=south] DUNSWE=NNOINN",
			"cesu[facing=west] DUNSWE=NNNNIO",
			"cesu[facing=east] DUNSWE=NNNNOI",
			"charge_pad[state=idle] DUNSWE=IIIIII",
			"charge_pad[state=charging] DUNSWE=IIIIII",
			"charge_pad[state=ready] DUNSWE=IIIIII",
			"charge_pad[state=empty] DUNSWE=IIIIII",
			"energy_condenser[lit=true] DUNSWE=IINNNN",
			"energy_condenser[lit=false] DUNSWE=IINNNN",
			"reactor_controller[facing=north,formed=true] DUNSWE=OONOOO",
			"reactor_controller[facing=north,formed=false] DUNSWE=OONOOO",
			"reactor_controller[facing=south,formed=true] DUNSWE=OOONOO",
			"reactor_controller[facing=south,formed=false] DUNSWE=OOONOO",
			"reactor_controller[facing=west,formed=true] DUNSWE=OOOONO",
			"reactor_controller[facing=west,formed=false] DUNSWE=OOOONO",
			"reactor_controller[facing=east,formed=true] DUNSWE=OOOOON",
			"reactor_controller[facing=east,formed=false] DUNSWE=OOOOON",
			"reactor_outlet[edge=true,formed=true] DUNSWE=OOOOOO",
			"reactor_outlet[edge=true,formed=false] DUNSWE=OOOOOO",
			"reactor_outlet[edge=false,formed=true] DUNSWE=OOOOOO",
			"reactor_outlet[edge=false,formed=false] DUNSWE=OOOOOO",
			"incubator[facing=north,lit=true] DUNSWE=IINIII",
			"incubator[facing=north,lit=false] DUNSWE=IINIII",
			"incubator[facing=south,lit=true] DUNSWE=IIINII",
			"incubator[facing=south,lit=false] DUNSWE=IIINII",
			"incubator[facing=west,lit=true] DUNSWE=IIIINI",
			"incubator[facing=west,lit=false] DUNSWE=IIIINI",
			"incubator[facing=east,lit=true] DUNSWE=IIIIIN",
			"incubator[facing=east,lit=false] DUNSWE=IIIIIN",
			"garden_drone_station[] DUNSWE=IIIIII",
			"crystal_farm_controller[facing=north,formed=true] DUNSWE=BBBBBB",
			"crystal_farm_controller[facing=north,formed=false] DUNSWE=BBBBBB",
			"crystal_farm_controller[facing=south,formed=true] DUNSWE=BBBBBB",
			"crystal_farm_controller[facing=south,formed=false] DUNSWE=BBBBBB",
			"crystal_farm_controller[facing=west,formed=true] DUNSWE=BBBBBB",
			"crystal_farm_controller[facing=west,formed=false] DUNSWE=BBBBBB",
			"crystal_farm_controller[facing=east,formed=true] DUNSWE=BBBBBB",
			"crystal_farm_controller[facing=east,formed=false] DUNSWE=BBBBBB",
			"sprinkler[hanging=true,spraying=true] DUNSWE=NNNNNN",
			"sprinkler[hanging=true,spraying=false] DUNSWE=NNNNNN",
			"sprinkler[hanging=false,spraying=true] DUNSWE=NNNNNN",
			"sprinkler[hanging=false,spraying=false] DUNSWE=NNNNNN",
			"mob_repeller[lit=true] DUNSWE=IIIIII",
			"mob_repeller[lit=false] DUNSWE=IIIIII",
			"mob_repeller_mv[lit=true] DUNSWE=IIIIII",
			"mob_repeller_mv[lit=false] DUNSWE=IIIIII",
			"mob_repeller_hv[lit=true] DUNSWE=IIIIII",
			"mob_repeller_hv[lit=false] DUNSWE=IIIIII");
}
