package dev.alaindustrial.gametest;

import java.util.List;

/**
 * Reviewed content-registry snapshot (MOD-699) that {@link RegistrySnapshotScenarios} compares both
 * loaders against. Blocks, block-entity → block pairs, menus, fluids and the shared registries (sounds, data
 * components, effects, particles, criteria); the items are in {@link RegistrySnapshotItems}.
 *
 * <p>Written by that scenario, and only on the explicit command below — never by {@code regen.py},
 * a hook, {@code new_machine.py} or a merge driver. Each Minecraft line captures its own reference
 * on its own branch: block properties differ between the lines on purpose.
 *
 * <p>Update command (absolute path to this directory; Fabric lane):
 * <pre>
 * JAVA_TOOL_OPTIONS="-Dfabric-api.gametest.filter=*:registry_snapshot_game_test_*
 *   -Dalaindustrial.registrySnapshot.writeTo=&lt;repo&gt;/common/src/gametest/java/dev/alaindustrial/gametest"
 *   ./gradlew :fabric:runGameTest
 * </pre>
 * The run fails on purpose after writing both files; review the diff, then commit it together with
 * the change that altered the registries.
 */
final class RegistrySnapshot {

	private RegistrySnapshot() {}

	/**
	 * {@code false} only in the hand-derived seed, which holds the composition without the block and
	 * item properties: the scenario then compares ids alone. The update command always writes {@code true}.
	 */
	static final boolean PROPERTIES_CAPTURED = true;

	/**
	 * Shipped ids deliberately removed, one {@code "<section> <id> — MOD-XXX <reason>"} each. The update
	 * command refuses to drop an id from {@link #LINES} unless it is announced here, and never adds a line.
	 */
	static final List<String> REMOVED = List.of();

	static final List<String> LINES = List.of(
			"block advanced_machine_casing destroy=6.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=8.0 map=NONE loot=alaindustrial:blocks/advanced_machine_casing",
			"block alloy_smelter destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/alloy_smelter",
			"block assembler destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/assembler",
			"block battery_box destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=WOOD blast=6.0 map=NONE loot=alaindustrial:blocks/battery_box",
			"block biofuel destroy=100.0 tool=no light=0 push=POPPED occludes=no sound=EMPTY blast=100.0 map=COLOR_GREEN replaceable liquid loot=none",
			"block broken_engraved_plate_b destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/broken_engraved_plate_b",
			"block broken_engraved_plate_d destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/broken_engraved_plate_d",
			"block broken_engraved_plate_k destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/broken_engraved_plate_k",
			"block broken_engraved_plate_m destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/broken_engraved_plate_m",
			"block broken_engraved_plate_p destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/broken_engraved_plate_p",
			"block broken_engraved_plate_r destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/broken_engraved_plate_r",
			"block broken_engraved_plate_w destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/broken_engraved_plate_w",
			"block canning_machine destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/canning_machine",
			"block carbon_ceramic destroy=4.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=CALCITE blast=30.0 map=NONE loot=alaindustrial:blocks/carbon_ceramic",
			"block cesu destroy=4.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/cesu",
			"block charge_pad destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE lightmax=10 loot=alaindustrial:blocks/charge_pad",
			"block component_repair_bench destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/component_repair_bench",
			"block compressor destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/compressor",
			"block concentrator_section destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/concentrator_section",
			"block copper_cable destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.5 map=NONE loot=alaindustrial:blocks/copper_cable",
			"block creative_energy_source destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/creative_energy_source",
			"block crystal_farm_controller destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/crystal_farm_controller",
			"block crystal_farm_door destroy=3.0 tool=yes light=0 push=POPPED occludes=no sound=COPPER blast=6.0 map=NONE loot=alaindustrial:blocks/crystal_farm_door",
			"block crystal_farm_floor destroy=3.0 tool=yes light=0 push=IMMOVEABLE occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/crystal_farm_floor",
			"block crystal_farm_glass destroy=3.0 tool=yes light=0 push=IMMOVEABLE occludes=no sound=GLASS blast=6.0 map=NONE loot=alaindustrial:blocks/crystal_farm_glass",
			"block crystal_seedbed destroy=3.0 tool=yes light=0 push=IMMOVEABLE occludes=yes sound=AMETHYST blast=6.0 map=NONE loot=alaindustrial:blocks/crystal_seedbed",
			"block daylight_solar_panel destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=GLASS blast=6.0 map=NONE loot=alaindustrial:blocks/daylight_solar_panel",
			"block deepslate_nickel_ore destroy=4.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=DEEPSLATE blast=3.0 map=NONE loot=alaindustrial:blocks/deepslate_nickel_ore",
			"block deepslate_silver_ore destroy=4.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=DEEPSLATE blast=3.0 map=NONE loot=alaindustrial:blocks/deepslate_silver_ore",
			"block deepslate_sulfur_ore destroy=4.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=DEEPSLATE blast=3.0 map=NONE loot=alaindustrial:blocks/deepslate_sulfur_ore",
			"block deepslate_tin_ore destroy=4.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=DEEPSLATE blast=3.0 map=NONE loot=alaindustrial:blocks/deepslate_tin_ore",
			"block deepslate_uranium_ore destroy=4.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=DEEPSLATE blast=3.0 map=NONE loot=alaindustrial:blocks/deepslate_uranium_ore",
			"block diamond_chest destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=1200.0 map=NONE loot=alaindustrial:blocks/diamond_chest",
			"block diesel destroy=100.0 tool=no light=0 push=POPPED occludes=no sound=EMPTY blast=100.0 map=COLOR_YELLOW replaceable liquid loot=none",
			"block distillation_column destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/distillation_column",
			"block distillation_column_middle destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/distillation_column_middle",
			"block distillation_column_top destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/distillation_column_top",
			"block electric_furnace destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/electric_furnace",
			"block electric_heater destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/electric_heater",
			"block electrum_cable destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.5 map=NONE loot=alaindustrial:blocks/electrum_cable",
			"block electrum_chest destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/electrum_chest",
			"block energy_condenser destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/energy_condenser",
			"block engraved_plate_0 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_0",
			"block engraved_plate_1 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_1",
			"block engraved_plate_2 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_2",
			"block engraved_plate_3 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_3",
			"block engraved_plate_4 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_4",
			"block engraved_plate_5 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_5",
			"block engraved_plate_6 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_6",
			"block engraved_plate_7 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_7",
			"block engraved_plate_8 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_8",
			"block engraved_plate_9 destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=POLISHED_DEEPSLATE blast=6.0 map=NONE loot=alaindustrial:blocks/engraved_plate_9",
			"block enriched_uranium_torch destroy=0.0 tool=no light=14 push=POPPED occludes=no sound=WOOD blast=0.0 map=NONE loot=alaindustrial:blocks/enriched_uranium_torch",
			"block enriched_uranium_wall_torch destroy=0.0 tool=no light=14 push=POPPED occludes=no sound=WOOD blast=0.0 map=NONE loot=alaindustrial:blocks/enriched_uranium_torch",
			"block extractor destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/extractor",
			"block fermenter destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/fermenter",
			"block fluid_pipe destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.5 map=NONE loot=alaindustrial:blocks/fluid_pipe",
			"block fluid_pipe_advanced destroy=0.3 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.6 map=NONE loot=alaindustrial:blocks/fluid_pipe_advanced",
			"block fluid_tank destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/fluid_tank",
			"block fluid_tank_advanced destroy=4.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=12.0 map=NONE loot=alaindustrial:blocks/fluid_tank_advanced",
			"block fuel_oil destroy=100.0 tool=no light=0 push=POPPED occludes=no sound=EMPTY blast=100.0 map=TERRACOTTA_BROWN replaceable liquid loot=none",
			"block fuel_rod_assembly destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/fuel_rod_assembly",
			"block galvanic_bath destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/galvanic_bath",
			"block garden_drone_station destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/garden_drone_station",
			"block generator destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/generator",
			"block geothermal_generator destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/geothermal_generator",
			"block gold_cable destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.5 map=NONE loot=alaindustrial:blocks/gold_cable",
			"block gold_chest destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/gold_chest",
			"block high_altitude_wind_mill destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/high_altitude_wind_mill",
			"block incubator destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/incubator",
			"block incubator_dome destroy=1.0 tool=yes light=0 push=IMMOVEABLE occludes=no sound=GLASS blast=2.0 map=NONE loot=alaindustrial:blocks/incubator_dome",
			"block industrial_workbench destroy=2.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/industrial_workbench",
			"block insulated_copper_cable destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=WOOL blast=0.5 map=NONE loot=alaindustrial:blocks/insulated_copper_cable",
			"block insulated_electrum_cable destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=WOOL blast=0.5 map=NONE loot=alaindustrial:blocks/insulated_electrum_cable",
			"block insulated_gold_cable destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=WOOL blast=0.5 map=NONE loot=alaindustrial:blocks/insulated_gold_cable",
			"block insulated_tin_cable destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=WOOL blast=0.5 map=NONE loot=alaindustrial:blocks/insulated_tin_cable",
			"block iron_chest destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/iron_chest",
			"block iron_furnace destroy=3.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/iron_furnace",
			"block irradiated_soil destroy=0.6 tool=no light=0 push=PUSH_PULL occludes=yes sound=GRAVEL blast=0.6 map=NONE loot=alaindustrial:blocks/irradiated_soil",
			"block item_pipe destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.5 map=NONE loot=alaindustrial:blocks/item_pipe",
			"block item_pipe_advanced destroy=0.3 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.6 map=NONE loot=alaindustrial:blocks/item_pipe_advanced",
			"block kok_sagyz destroy=0.0 tool=no light=0 push=POPPED occludes=no sound=GRASS blast=0.0 map=NONE loot=alaindustrial:blocks/kok_sagyz",
			"block kok_sagyz_root destroy=0.6 tool=no light=0 push=PUSH_PULL occludes=yes sound=ROOTED_DIRT blast=0.6 map=NONE loot=alaindustrial:blocks/kok_sagyz_root",
			"block lightning_rod_generator destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/lightning_rod_generator",
			"block macerator destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/macerator",
			"block machine_casing destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/machine_casing",
			"block mob_repeller destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=14 loot=alaindustrial:blocks/mob_repeller",
			"block mob_repeller_hv destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=14 loot=alaindustrial:blocks/mob_repeller_hv",
			"block mob_repeller_mv destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=14 loot=alaindustrial:blocks/mob_repeller_mv",
			"block mob_wheel_cell destroy=2.0 tool=yes light=0 push=IMMOVEABLE occludes=no sound=WOOD blast=3.0 map=NONE loot=alaindustrial:blocks/mob_wheel_cell",
			"block mob_wheel_controller destroy=2.0 tool=yes light=0 push=IMMOVEABLE occludes=no sound=WOOD blast=3.0 map=NONE loot=alaindustrial:blocks/mob_wheel_controller",
			"block mob_wheel_frame destroy=2.0 tool=yes light=0 push=IMMOVEABLE occludes=no sound=WOOD blast=3.0 map=NONE loot=alaindustrial:blocks/mob_wheel_frame",
			"block mob_wheel_gate destroy=2.0 tool=yes light=0 push=IMMOVEABLE occludes=no sound=WOOD blast=3.0 map=NONE loot=alaindustrial:blocks/mob_wheel_gate",
			"block mob_wheel_rotor destroy=2.0 tool=yes light=0 push=IMMOVEABLE occludes=no sound=WOOD blast=3.0 map=NONE loot=alaindustrial:blocks/mob_wheel_rotor",
			"block monitor_core destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/monitor_core",
			"block monitor_panel destroy=2.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=4.0 map=NONE loot=alaindustrial:blocks/monitor_panel",
			"block moonlit_solar_panel destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=GLASS blast=6.0 map=NONE loot=alaindustrial:blocks/moonlit_solar_panel",
			"block nickel_ore destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=STONE blast=3.0 map=NONE loot=alaindustrial:blocks/nickel_ore",
			"block nutrient_solution destroy=100.0 tool=no light=0 push=POPPED occludes=no sound=EMPTY blast=100.0 map=EMERALD replaceable liquid loot=none",
			"block oil destroy=100.0 tool=no light=0 push=POPPED occludes=no sound=EMPTY blast=100.0 map=COLOR_BLACK replaceable liquid loot=none",
			"block oil_fire destroy=0.0 tool=no light=15 push=POPPED occludes=no sound=WOOL blast=0.0 map=FIRE replaceable loot=none",
			"block palladium_ore destroy=4.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=NETHER_ORE blast=1200.0 map=NONE loot=alaindustrial:blocks/palladium_ore",
			"block polymerizer destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/polymerizer",
			"block pump destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/pump",
			"block radiant_solar_panel destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/radiant_solar_panel",
			"block reactor_button destroy=0.5 tool=no light=0 push=POPPED occludes=no sound=IRON blast=0.5 map=NONE loot=alaindustrial:blocks/reactor_button",
			"block reactor_casing destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=30.0 map=NONE loot=alaindustrial:blocks/reactor_casing",
			"block reactor_controller destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=30.0 map=NONE loot=alaindustrial:blocks/reactor_controller",
			"block reactor_door destroy=5.0 tool=yes light=0 push=POPPED occludes=no sound=METAL blast=30.0 map=NONE loot=alaindustrial:blocks/reactor_door",
			"block reactor_glass destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=GLASS blast=30.0 map=NONE loot=alaindustrial:blocks/reactor_glass",
			"block reactor_lamp destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=30.0 map=NONE loot=alaindustrial:blocks/reactor_lamp",
			"block reactor_lever destroy=0.5 tool=no light=0 push=POPPED occludes=no sound=METAL blast=0.5 map=NONE loot=alaindustrial:blocks/reactor_lever",
			"block reactor_outlet destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=30.0 map=NONE loot=alaindustrial:blocks/reactor_outlet",
			"block reactor_port destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=30.0 map=NONE loot=alaindustrial:blocks/reactor_port",
			"block rectification_section destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/rectification_section",
			"block recycler destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/recycler",
			"block reinforced_fluid_pipe destroy=1.5 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=12.0 map=NONE loot=alaindustrial:blocks/reinforced_fluid_pipe",
			"block reinforced_steam_pipe destroy=1.5 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=12.0 map=NONE loot=alaindustrial:blocks/reinforced_steam_pipe",
			"block sawmill destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/sawmill",
			"block shielding_chest destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/shielding_chest",
			"block silver_chest destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/silver_chest",
			"block silver_ore destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=STONE blast=3.0 map=NONE loot=alaindustrial:blocks/silver_ore",
			"block silver_plate_block destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/silver_plate_block",
			"block slag_block destroy=2.5 tool=yes light=0 push=PUSH_PULL occludes=yes sound=STONE blast=6.0 map=NONE loot=alaindustrial:blocks/slag_block",
			"block smart_wire destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.5 map=NONE loot=alaindustrial:blocks/smart_wire",
			"block solar_panel destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=GLASS blast=6.0 map=NONE loot=alaindustrial:blocks/solar_panel",
			"block soot_layer destroy=0.1 tool=yes light=0 push=POPPED occludes=no sound=SAND blast=0.1 map=COLOR_BLACK loot=alaindustrial:blocks/soot_layer",
			"block sprinkler destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/sprinkler",
			"block steam_nozzle destroy=4.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=20.0 map=NONE loot=alaindustrial:blocks/steam_nozzle",
			"block steam_pipe destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.5 map=NONE loot=alaindustrial:blocks/steam_pipe",
			"block storage_module destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/storage_module",
			"block storm_wind_mill destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/storm_wind_mill",
			"block sulfur_ore destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=STONE blast=3.0 map=NONE loot=alaindustrial:blocks/sulfur_ore",
			"block teleporter destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=12.0 map=NONE loot=alaindustrial:blocks/teleporter",
			"block teleporter_capsule destroy=1.0 tool=yes light=0 push=IMMOVEABLE occludes=no sound=GLASS blast=2.0 map=NONE loot=alaindustrial:blocks/teleporter_capsule",
			"block tempered_iron_block destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/tempered_iron_block",
			"block tempered_iron_plate_block destroy=5.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/tempered_iron_plate_block",
			"block thermal_centrifuge destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=no sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/thermal_centrifuge",
			"block tin_cable destroy=0.2 tool=yes light=0 push=PUSH_PULL occludes=no sound=COPPER blast=0.5 map=NONE loot=alaindustrial:blocks/tin_cable",
			"block tin_ore destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=STONE blast=3.0 map=NONE loot=alaindustrial:blocks/tin_ore",
			"block trellis destroy=0.2 tool=no light=0 push=POPPED occludes=no sound=GRASS blast=0.2 map=NONE loot=alaindustrial:blocks/trellis",
			"block upgrade_table destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/upgrade_table",
			"block uranium_ore destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=STONE blast=3.0 map=NONE loot=alaindustrial:blocks/uranium_ore",
			"block vulcanizer destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE lightmax=13 loot=alaindustrial:blocks/vulcanizer",
			"block water_mill destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/water_mill",
			"block wind_mill destroy=3.0 tool=yes light=0 push=PUSH_PULL occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/wind_mill",
			"block workstation destroy=3.0 tool=yes light=0 push=IMMOVEABLE occludes=yes sound=METAL blast=6.0 map=NONE loot=alaindustrial:blocks/workstation",
			"block_entity alloy_smelter:alloy_smelter",
			"block_entity assembler:assembler",
			"block_entity battery_box:battery_box",
			"block_entity canning_machine:canning_machine",
			"block_entity cesu:cesu",
			"block_entity charge_pad:charge_pad",
			"block_entity component_repair_bench:component_repair_bench",
			"block_entity compressor:compressor",
			"block_entity copper_cable:copper_cable",
			"block_entity copper_cable:electrum_cable",
			"block_entity copper_cable:gold_cable",
			"block_entity copper_cable:insulated_copper_cable",
			"block_entity copper_cable:insulated_electrum_cable",
			"block_entity copper_cable:insulated_gold_cable",
			"block_entity copper_cable:insulated_tin_cable",
			"block_entity copper_cable:tin_cable",
			"block_entity creative_energy_source:creative_energy_source",
			"block_entity crystal_farm_controller:crystal_farm_controller",
			"block_entity daylight_solar_panel:daylight_solar_panel",
			"block_entity diamond_chest:diamond_chest",
			"block_entity distillation_column:distillation_column",
			"block_entity distillation_column_segment:distillation_column_middle",
			"block_entity distillation_column_segment:distillation_column_top",
			"block_entity electric_furnace:electric_furnace",
			"block_entity electric_heater:electric_heater",
			"block_entity electrum_chest:electrum_chest",
			"block_entity energy_condenser:energy_condenser",
			"block_entity extractor:extractor",
			"block_entity fermenter:fermenter",
			"block_entity fluid_pipe:fluid_pipe",
			"block_entity fluid_pipe:fluid_pipe_advanced",
			"block_entity fluid_pipe:reinforced_fluid_pipe",
			"block_entity fluid_pipe:reinforced_steam_pipe",
			"block_entity fluid_pipe:steam_pipe",
			"block_entity fluid_tank:fluid_tank",
			"block_entity fluid_tank:fluid_tank_advanced",
			"block_entity fuel_rod_assembly:fuel_rod_assembly",
			"block_entity galvanic_bath:galvanic_bath",
			"block_entity garden_drone_station:garden_drone_station",
			"block_entity generator:generator",
			"block_entity geothermal_generator:geothermal_generator",
			"block_entity gold_chest:gold_chest",
			"block_entity high_altitude_wind_mill:high_altitude_wind_mill",
			"block_entity incubator:incubator",
			"block_entity industrial_workbench:industrial_workbench",
			"block_entity iron_chest:iron_chest",
			"block_entity iron_furnace:iron_furnace",
			"block_entity item_pipe:item_pipe",
			"block_entity item_pipe:item_pipe_advanced",
			"block_entity kok_sagyz_root:kok_sagyz_root",
			"block_entity lightning_rod_generator:lightning_rod_generator",
			"block_entity macerator:macerator",
			"block_entity mob_repeller:mob_repeller",
			"block_entity mob_repeller_hv:mob_repeller_hv",
			"block_entity mob_repeller_mv:mob_repeller_mv",
			"block_entity mob_wheel_controller:mob_wheel_controller",
			"block_entity monitor_core:monitor_core",
			"block_entity monitor_panel:monitor_panel",
			"block_entity moonlit_solar_panel:moonlit_solar_panel",
			"block_entity polymerizer:polymerizer",
			"block_entity pump:pump",
			"block_entity radiant_solar_panel:radiant_solar_panel",
			"block_entity reactor_controller:reactor_controller",
			"block_entity reactor_door:reactor_door",
			"block_entity reactor_outlet:reactor_outlet",
			"block_entity reactor_port:reactor_port",
			"block_entity recycler:recycler",
			"block_entity sawmill:sawmill",
			"block_entity shielding_chest:shielding_chest",
			"block_entity silver_chest:silver_chest",
			"block_entity smart_wire:smart_wire",
			"block_entity solar_panel:solar_panel",
			"block_entity sprinkler:sprinkler",
			"block_entity steam_nozzle:steam_nozzle",
			"block_entity storage_module:storage_module",
			"block_entity storm_wind_mill:storm_wind_mill",
			"block_entity teleporter:teleporter",
			"block_entity thermal_centrifuge:thermal_centrifuge",
			"block_entity upgrade_table:upgrade_table",
			"block_entity vulcanizer:vulcanizer",
			"block_entity water_mill:water_mill",
			"block_entity wind_mill:wind_mill",
			"block_entity workstation:workstation",
			"block_entity_type alloy_smelter",
			"block_entity_type assembler",
			"block_entity_type battery_box",
			"block_entity_type canning_machine",
			"block_entity_type cesu",
			"block_entity_type charge_pad",
			"block_entity_type component_repair_bench",
			"block_entity_type compressor",
			"block_entity_type copper_cable",
			"block_entity_type creative_energy_source",
			"block_entity_type crystal_farm_controller",
			"block_entity_type daylight_solar_panel",
			"block_entity_type diamond_chest",
			"block_entity_type distillation_column",
			"block_entity_type distillation_column_segment",
			"block_entity_type electric_furnace",
			"block_entity_type electric_heater",
			"block_entity_type electrum_chest",
			"block_entity_type energy_condenser",
			"block_entity_type extractor",
			"block_entity_type fermenter",
			"block_entity_type fluid_pipe",
			"block_entity_type fluid_tank",
			"block_entity_type fuel_rod_assembly",
			"block_entity_type galvanic_bath",
			"block_entity_type garden_drone_station",
			"block_entity_type generator",
			"block_entity_type geothermal_generator",
			"block_entity_type gold_chest",
			"block_entity_type high_altitude_wind_mill",
			"block_entity_type incubator",
			"block_entity_type industrial_workbench",
			"block_entity_type iron_chest",
			"block_entity_type iron_furnace",
			"block_entity_type item_pipe",
			"block_entity_type kok_sagyz_root",
			"block_entity_type lightning_rod_generator",
			"block_entity_type macerator",
			"block_entity_type mob_repeller",
			"block_entity_type mob_repeller_hv",
			"block_entity_type mob_repeller_mv",
			"block_entity_type mob_wheel_controller",
			"block_entity_type monitor_core",
			"block_entity_type monitor_panel",
			"block_entity_type moonlit_solar_panel",
			"block_entity_type polymerizer",
			"block_entity_type pump",
			"block_entity_type radiant_solar_panel",
			"block_entity_type reactor_controller",
			"block_entity_type reactor_door",
			"block_entity_type reactor_outlet",
			"block_entity_type reactor_port",
			"block_entity_type recycler",
			"block_entity_type sawmill",
			"block_entity_type shielding_chest",
			"block_entity_type silver_chest",
			"block_entity_type smart_wire",
			"block_entity_type solar_panel",
			"block_entity_type sprinkler",
			"block_entity_type steam_nozzle",
			"block_entity_type storage_module",
			"block_entity_type storm_wind_mill",
			"block_entity_type teleporter",
			"block_entity_type thermal_centrifuge",
			"block_entity_type upgrade_table",
			"block_entity_type vulcanizer",
			"block_entity_type water_mill",
			"block_entity_type wind_mill",
			"block_entity_type workstation",
			"data_component_type blueprint_pattern",
			"data_component_type blueprint_result",
			"data_component_type blueprint_substitute",
			"data_component_type cable_color",
			"data_component_type capsule_fluid",
			"data_component_type distillation_column_contents",
			"data_component_type drill_column_enabled",
			"data_component_type drill_upgrades",
			"data_component_type electric_bow_charged",
			"data_component_type fluid_tank_contents",
			"data_component_type geiger_alert",
			"data_component_type item_modules",
			"data_component_type magnet_enabled",
			"data_component_type magnet_filter",
			"data_component_type mutation_grade",
			"data_component_type network_analyzer_mode",
			"data_component_type network_scan",
			"data_component_type pouch_contents",
			"data_component_type pouch_energy",
			"data_component_type repair_count",
			"data_component_type saber_active",
			"data_component_type soul_vessel_kills",
			"data_component_type step_assist_enabled",
			"data_component_type stored_energy",
			"data_component_type teleporter_log",
			"data_component_type teleporter_owner",
			"data_component_type teleporter_points",
			"data_component_type teleporter_private",
			"data_component_type teleporter_rtp_module",
			"fluid biofuel",
			"fluid diesel",
			"fluid flowing_biofuel",
			"fluid flowing_diesel",
			"fluid flowing_fuel_oil",
			"fluid flowing_nutrient_solution",
			"fluid flowing_oil",
			"fluid fuel_oil",
			"fluid nutrient_solution",
			"fluid oil",
			"fluid steam",
			"menu alloy_smelter",
			"menu assembler",
			"menu battery_box",
			"menu canning_machine",
			"menu cesu",
			"menu charge_pad",
			"menu component_repair_bench",
			"menu compressor",
			"menu creative_energy_source",
			"menu daylight_solar_panel",
			"menu diamond_chest",
			"menu distillation_column",
			"menu double_chest",
			"menu electric_furnace",
			"menu electric_heater",
			"menu electrum_chest",
			"menu energy_condenser",
			"menu extractor",
			"menu fermenter",
			"menu galvanic_bath",
			"menu garden_drone_station",
			"menu generator",
			"menu geothermal_generator",
			"menu gold_chest",
			"menu high_altitude_wind_mill",
			"menu incubator",
			"menu iron_chest",
			"menu lightning_rod_generator",
			"menu macerator",
			"menu magnet",
			"menu mob_repeller",
			"menu mob_repeller_hv",
			"menu mob_repeller_mv",
			"menu mob_wheel_controller",
			"menu monitor_core",
			"menu moonlit_solar_panel",
			"menu polymerizer",
			"menu pump",
			"menu radiant_solar_panel",
			"menu reactor_controller",
			"menu recycler",
			"menu sawmill",
			"menu shielding_chest",
			"menu silver_chest",
			"menu solar_panel",
			"menu sprinkler",
			"menu storage_module_3",
			"menu storage_module_6",
			"menu storm_wind_mill",
			"menu teleporter_remote",
			"menu teleporter_station",
			"menu thermal_centrifuge",
			"menu upgrade_table",
			"menu vulcanizer",
			"menu water_mill",
			"menu wind_mill",
			"mob_effect radiation",
			"particle_type enriched_uranium_flame",
			"particle_type nutrient_spray",
			"sound_event alloy_smelter_hum",
			"sound_event block.steam_nozzle.vent",
			"sound_event canning_machine_hum",
			"sound_event charge_pad_done",
			"sound_event charge_pad_hum",
			"sound_event component_repair_bench_hum",
			"sound_event compressor_hum",
			"sound_event electric_furnace",
			"sound_event electric_heater_hum",
			"sound_event energy_condenser_hum",
			"sound_event extractor_hum",
			"sound_event fermenter_hum",
			"sound_event galvanic_bath_hum",
			"sound_event garden_drone_fly",
			"sound_event geiger_click",
			"sound_event generator_hum",
			"sound_event incubator_hum",
			"sound_event iron_chest_close",
			"sound_event iron_chest_open",
			"sound_event macerator_grind",
			"sound_event mob_repeller_hum",
			"sound_event polymerizer_hum",
			"sound_event pump_hum",
			"sound_event reactor_alarm",
			"sound_event reactor_door_close",
			"sound_event reactor_door_open",
			"sound_event reactor_hum",
			"sound_event reactor_spindown",
			"sound_event recycler_hum",
			"sound_event sawmill_hum",
			"sound_event scythe_swing",
			"sound_event solar_panel_hum",
			"sound_event water_mill_hum",
			"sound_event wind_mill_hum",
			"trigger_type mutation_completed",
			"trigger_type network_energized",
			"trigger_type reactor_milestone");
}
