package dev.alaindustrial.gametest;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import net.minecraft.core.Holder;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.Registries;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.BiomeTags;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.biome.Biomes;
import net.minecraft.world.level.levelgen.GenerationStep;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;

/**
 * L2 characterization of worldgen injection (MOD-702, MISC-6): every placed feature the mod ships is
 * generated by the biomes of its selector, at the step its entrance spec names, and by no biome
 * outside it — on BOTH loaders, read back through the same generation settings
 * ({@link BiomeFeatureProbe}).
 *
 * <p>The two loaders inject the same twelve features by different means and by different selectors:
 * Fabric in code ({@code ModWorldGen} → {@code BiomeModifications.addFeature}), NeoForge through eight
 * {@code neoforge/biome_modifier/*.json} files, and no gate compares the two lists. A feature one
 * loader forgot, put on the wrong step or aimed at another selector turns the scenario of that
 * feature red on that loader only. The scenarios pin the CURRENT behaviour; a divergence they find is a
 * defect to be filed, not data to be edited here.
 *
 * <p><b>The ores' biomes are read from the running world, never named.</b> Fabric injects the five ores
 * with {@code BiomeSelectors.foundInOverworld()}, which asks the overworld's own biome source which
 * biomes it can generate; NeoForge takes {@code #minecraft:is_overworld}. The game-test world is a flat
 * overworld of ONE biome, and which one depends on the game version: vanilla {@code GameTestServer}
 * builds {@code WorldPresets.FLAT} (plains) on 26.2 and {@code FLAT_ALL_DIMENSIONS} (desert) on 26.3.
 * A named biome the world cannot generate is left out by Fabric with no defect, so the ores are
 * probed in every biome the overworld of THIS world can generate that also carries
 * {@code #minecraft:is_overworld} — the biomes both selectors take ({@link #overworldBiomesOfThisWorld}).
 * That set must not be empty, so a forgotten ore cannot pass for want of a biome to ask. The selector
 * difference itself (a modded overworld biome the Fabric selector misses) cannot be seen from here.
 *
 * <p>Biomes outside a selector are probed at EVERY step, not only at the feature's own: a feature on a
 * second step is as wrong as one in a second biome.
 */
public final class WorldgenInjectionScenarios {

	/** This class's world gametests for both loaders (ADR-038); nested so reading them does not initialise it. */
	public static final class Roster {
		public static final List<RosterEntry> ENTRIES = List.of(
				RosterEntry.of(WorldgenInjectionScenarios::oilLakeUndergroundIsInjected,
								"worldgen_oil_lake_underground_is_injected")
						.fabricId("WorldgenInjectionGameTest", "oilLakeUndergroundIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::oilLakeDeepIsInjected, "worldgen_oil_lake_deep_is_injected")
						.fabricId("WorldgenInjectionGameTest", "oilLakeDeepIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::oilLakeSurfaceIsInjected,
								"worldgen_oil_lake_surface_is_injected")
						.fabricId("WorldgenInjectionGameTest", "oilLakeSurfaceIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::oilGeyserIsInjected, "worldgen_oil_geyser_is_injected")
						.fabricId("WorldgenInjectionGameTest", "oilGeyserIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::tinOreIsInjected, "worldgen_tin_ore_is_injected")
						.fabricId("WorldgenInjectionGameTest", "tinOreIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::silverOreIsInjected, "worldgen_silver_ore_is_injected")
						.fabricId("WorldgenInjectionGameTest", "silverOreIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::nickelOreIsInjected, "worldgen_nickel_ore_is_injected")
						.fabricId("WorldgenInjectionGameTest", "nickelOreIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::sulfurOreIsInjected, "worldgen_sulfur_ore_is_injected")
						.fabricId("WorldgenInjectionGameTest", "sulfurOreIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::uraniumOreIsInjected, "worldgen_uranium_ore_is_injected")
						.fabricId("WorldgenInjectionGameTest", "uraniumOreIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::palladiumOreIsInjected, "worldgen_palladium_ore_is_injected")
						.fabricId("WorldgenInjectionGameTest", "palladiumOreIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::abandonedLabIsInjected, "worldgen_abandoned_lab_is_injected")
						.fabricId("WorldgenInjectionGameTest", "abandonedLabIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::kokSagyzIsInjected, "worldgen_kok_sagyz_is_injected")
						.fabricId("WorldgenInjectionGameTest", "kokSagyzIsInjected").ticks(20, 100),
				RosterEntry.of(WorldgenInjectionScenarios::everyShippedPlacedFeatureHasAnInjectionScenario,
								"worldgen_every_shipped_placed_feature_has_an_injection_scenario")
						.fabricId("WorldgenInjectionGameTest", "everyShippedPlacedFeatureHasAnInjectionScenario")
						.ticks(20, 100));

		private Roster() {}
	}

	private WorldgenInjectionScenarios() {}

	/** The biomes that must carry a feature, resolved in the running world. */
	@FunctionalInterface
	private interface Carriers {
		List<ResourceKey<Biome>> in(GameTestHelper helper);

		/** The same biomes in every world: for features injected by tag or by biome id. */
		static Carriers fixed(List<ResourceKey<Biome>> biomes) {
			return helper -> biomes;
		}
	}

	/** One placed feature: the step it belongs to, biomes that must carry it, biomes that must not. */
	private record Injection(String feature, GenerationStep.Decoration step,
			Carriers carriers, List<ResourceKey<Biome>> bystanders) {}

	/** Overworld biomes both selectors take, and the dimensions' biomes both leave out. */
	private static final Carriers OVERWORLD_CARRIERS = Carriers.fixed(List.of(Biomes.PLAINS, Biomes.DESERT));
	private static final Carriers ORE_CARRIERS = WorldgenInjectionScenarios::overworldBiomesOfThisWorld;
	private static final List<ResourceKey<Biome>> NOT_OVERWORLD = List.of(Biomes.NETHER_WASTES, Biomes.THE_END);

	private static final Injection OIL_LAKE_UNDERGROUND = new Injection("oil_lake_underground",
			GenerationStep.Decoration.LAKES, OVERWORLD_CARRIERS, NOT_OVERWORLD);
	private static final Injection OIL_LAKE_DEEP = new Injection("oil_lake_deep",
			GenerationStep.Decoration.LAKES, OVERWORLD_CARRIERS, NOT_OVERWORLD);
	private static final Injection OIL_LAKE_SURFACE = new Injection("oil_lake_surface",
			GenerationStep.Decoration.LAKES, OVERWORLD_CARRIERS, NOT_OVERWORLD);
	private static final Injection OIL_GEYSER = new Injection("oil_geyser",
			GenerationStep.Decoration.LAKES, OVERWORLD_CARRIERS, NOT_OVERWORLD);
	private static final Injection TIN_ORE = new Injection("tin_ore",
			GenerationStep.Decoration.UNDERGROUND_ORES, ORE_CARRIERS, NOT_OVERWORLD);
	private static final Injection SILVER_ORE = new Injection("silver_ore",
			GenerationStep.Decoration.UNDERGROUND_ORES, ORE_CARRIERS, NOT_OVERWORLD);
	private static final Injection NICKEL_ORE = new Injection("nickel_ore",
			GenerationStep.Decoration.UNDERGROUND_ORES, ORE_CARRIERS, NOT_OVERWORLD);
	private static final Injection SULFUR_ORE = new Injection("sulfur_ore",
			GenerationStep.Decoration.UNDERGROUND_ORES, ORE_CARRIERS, NOT_OVERWORLD);
	private static final Injection URANIUM_ORE = new Injection("uranium_ore",
			GenerationStep.Decoration.UNDERGROUND_ORES, ORE_CARRIERS, NOT_OVERWORLD);
	/** {@code has_palladium_ore} is {@code #c:is_nether}: the Nether carries it, the overworld does not. */
	private static final Injection PALLADIUM_ORE = new Injection("palladium_ore",
			GenerationStep.Decoration.UNDERGROUND_ORES, Carriers.fixed(List.of(Biomes.NETHER_WASTES)),
			List.of(Biomes.PLAINS, Biomes.DESERT, Biomes.THE_END));
	/** The same biomes as {@code AbandonedLabScenarios#labIsInjectedIntoItsBiomes}, the tag's land biomes. */
	private static final Injection ABANDONED_LAB = new Injection("abandoned_lab",
			GenerationStep.Decoration.SURFACE_STRUCTURES,
			Carriers.fixed(List.of(Biomes.PLAINS, Biomes.SNOWY_PLAINS, Biomes.JUNGLE)),
			List.of(Biomes.OCEAN, Biomes.RIVER, Biomes.DEEP_DARK));
	/** {@code has_kok_sagyz} lists six explicit biomes; plains were dropped from it in MOD-584. */
	private static final Injection KOK_SAGYZ = new Injection("kok_sagyz",
			GenerationStep.Decoration.VEGETAL_DECORATION, Carriers.fixed(List.of(Biomes.SAVANNA, Biomes.MEADOW)),
			List.of(Biomes.PLAINS, Biomes.DESERT));

	private static final List<Injection> ALL = List.of(OIL_LAKE_UNDERGROUND, OIL_LAKE_DEEP, OIL_LAKE_SURFACE,
			OIL_GEYSER, TIN_ORE, SILVER_ORE, NICKEL_ORE, SULFUR_ORE, URANIUM_ORE, PALLADIUM_ORE, ABANDONED_LAB,
			KOK_SAGYZ);

	/** The underground oil lakes are injected into the overworld's biomes at the lakes step. */
	public static void oilLakeUndergroundIsInjected(GameTestHelper helper) {
		verify(helper, OIL_LAKE_UNDERGROUND);
	}

	/** The deep oil lakes are injected into the overworld's biomes at the lakes step. */
	public static void oilLakeDeepIsInjected(GameTestHelper helper) {
		verify(helper, OIL_LAKE_DEEP);
	}

	/** The surface oil patches are injected into the overworld's biomes at the lakes step. */
	public static void oilLakeSurfaceIsInjected(GameTestHelper helper) {
		verify(helper, OIL_LAKE_SURFACE);
	}

	/** The oil geysers are injected into the overworld's biomes at the lakes step. */
	public static void oilGeyserIsInjected(GameTestHelper helper) {
		verify(helper, OIL_GEYSER);
	}

	/** Tin ore is injected into the overworld's biomes at the underground-ores step. */
	public static void tinOreIsInjected(GameTestHelper helper) {
		verify(helper, TIN_ORE);
	}

	/** Silver ore is injected into the overworld's biomes at the underground-ores step. */
	public static void silverOreIsInjected(GameTestHelper helper) {
		verify(helper, SILVER_ORE);
	}

	/** Nickel ore is injected into the overworld's biomes at the underground-ores step. */
	public static void nickelOreIsInjected(GameTestHelper helper) {
		verify(helper, NICKEL_ORE);
	}

	/** Sulfur ore is injected into the overworld's biomes at the underground-ores step. */
	public static void sulfurOreIsInjected(GameTestHelper helper) {
		verify(helper, SULFUR_ORE);
	}

	/** Uranium ore is injected into the overworld's biomes at the underground-ores step. */
	public static void uraniumOreIsInjected(GameTestHelper helper) {
		verify(helper, URANIUM_ORE);
	}

	/** Palladium ore is injected into the Nether's biomes, and not the overworld's. */
	public static void palladiumOreIsInjected(GameTestHelper helper) {
		verify(helper, PALLADIUM_ORE);
	}

	/** The abandoned lab is injected into the biomes of its tag at the surface-structures step. */
	public static void abandonedLabIsInjected(GameTestHelper helper) {
		verify(helper, ABANDONED_LAB);
	}

	/** Wild kok-sagyz is injected into the biomes of its tag at the vegetal-decoration step. */
	public static void kokSagyzIsInjected(GameTestHelper helper) {
		verify(helper, KOK_SAGYZ);
	}

	/**
	 * The scenarios above cover every placed feature the mod ships: a thirteenth feature
	 * added to {@code data/alaindustrial/worldgen/placed_feature/} without a row here fails.
	 */
	public static void everyShippedPlacedFeatureHasAnInjectionScenario(GameTestHelper helper) {
		Set<String> shipped = new TreeSet<>();
		for (Identifier id : helper.getLevel().registryAccess().lookupOrThrow(Registries.PLACED_FEATURE).keySet()) {
			if ("alaindustrial".equals(id.getNamespace())) {
				shipped.add(id.getPath());
			}
		}
		Set<String> covered = new TreeSet<>();
		for (Injection injection : ALL) {
			covered.add(injection.feature());
		}
		if (!shipped.equals(covered)) {
			Set<String> uncovered = new TreeSet<>(shipped);
			uncovered.removeAll(covered);
			Set<String> missing = new TreeSet<>(covered);
			missing.removeAll(shipped);
			helper.fail("placed features without an injection scenario: " + uncovered
					+ "; scenario rows whose placed feature is not loaded: " + missing);
			return;
		}
		helper.succeed();
	}

	/**
	 * The overworld biomes both ore selectors take in this world: every biome the overworld's biome
	 * source can generate (what {@code foundInOverworld()} asks) that also carries
	 * {@code #minecraft:is_overworld} (the NeoForge selector), sorted by id for a stable message.
	 */
	private static List<ResourceKey<Biome>> overworldBiomesOfThisWorld(GameTestHelper helper) {
		Registry<Biome> biomes = helper.getLevel().registryAccess().lookupOrThrow(Registries.BIOME);
		Set<ResourceKey<Biome>> found = new TreeSet<>(Comparator.comparing(key -> key.identifier().toString()));
		for (Holder<Biome> holder : helper.getLevel().getServer().overworld().getChunkSource().getGenerator()
				.getBiomeSource().possibleBiomes()) {
			holder.unwrapKey().filter(key -> biomes.getOrThrow(key).is(BiomeTags.IS_OVERWORLD)).ifPresent(found::add);
		}
		return List.copyOf(found);
	}

	/** Collects EVERY mismatch of one feature, so a first run names all of them, not the first only. */
	private static void verify(GameTestHelper helper, Injection injection) {
		ResourceKey<PlacedFeature> feature = BiomeFeatureProbe.placed(injection.feature());
		List<String> problems = new ArrayList<>();
		List<ResourceKey<Biome>> carriers = injection.carriers().in(helper);
		if (carriers.isEmpty()) {
			problems.add("no biome to probe: the overworld of this world generates no biome both selectors take");
		}
		for (ResourceKey<Biome> biome : carriers) {
			List<GenerationStep.Decoration> steps = BiomeFeatureProbe.stepsOf(helper, biome, feature);
			if (!steps.contains(injection.step())) {
				problems.add("not generated in " + biome.identifier() + " at " + injection.step()
						+ " (generated at steps: " + steps + ")");
			}
		}
		for (ResourceKey<Biome> biome : injection.bystanders()) {
			List<GenerationStep.Decoration> steps = BiomeFeatureProbe.stepsOf(helper, biome, feature);
			if (!steps.isEmpty()) {
				problems.add("generated in " + biome.identifier() + " (steps: " + steps
						+ "), which its selector leaves out");
			}
		}
		if (!problems.isEmpty()) {
			helper.fail(injection.feature() + ": " + String.join("; ", problems));
			return;
		}
		helper.succeed();
	}
}
