package dev.alaindustrial.registry;

import java.util.List;

/**
 * Reviewed registration order of {@link ContentManifest}'s four lists (MOD-711), which
 * {@link ContentManifestOrderTest} compares against. One line per entry, in list order:
 * {@code block <id>}, {@code item <id>}, {@code block_entity <id>: <valid blocks in blockSet() order>},
 * {@code menu <id>}.
 *
 * <p>Written only by the explicit command below — never by {@code regen.py}, a hook or a merge driver
 * (ADR-032). A change here is either a declared reordering (MOD-711 batch 3: entries moved between
 * domains) or content added or removed on purpose; review the diff as such.
 *
 * <p>Update command (absolute path to this directory):
 * <pre>
 * JAVA_TOOL_OPTIONS="-Dalaindustrial.manifestOrder.writeTo=&lt;repo&gt;/neoforge/src/test/java/dev/alaindustrial/registry"
 *   ./gradlew :neoforge:test --tests dev.alaindustrial.registry.ContentManifestOrderTest
 * </pre>
 * The run fails on purpose after writing the file.
 */
final class ContentManifestOrder {

	private ContentManifestOrder() {}

	static final List<String> LINES = List.of(
			"block generator",
			"block solar_panel",
			"block moonlit_solar_panel",
			"block daylight_solar_panel",
			"block radiant_solar_panel",
			"block concentrator_section",
			"block geothermal_generator",
			"block water_mill",
			"block wind_mill",
			"block high_altitude_wind_mill",
			"block storm_wind_mill",
			"block lightning_rod_generator",
			"block creative_energy_source",
			"block mob_wheel_controller",
			"block mob_wheel_frame",
			"block mob_wheel_rotor",
			"block mob_wheel_gate",
			"block mob_wheel_cell",
			"block piezo_plate",
			"block silent_piezo_plate",
			"block copper_cable",
			"block tin_cable",
			"block gold_cable",
			"block electrum_cable",
			"block insulated_copper_cable",
			"block insulated_tin_cable",
			"block insulated_gold_cable",
			"block insulated_electrum_cable",
			"block macerator",
			"block teleporter",
			"block teleporter_capsule",
			"block electric_furnace",
			"block iron_furnace",
			"block extractor",
			"block compressor",
			"block component_repair_bench",
			"block canning_machine",
			"block sawmill",
			"block assembler",
			"block polymerizer",
			"block alloy_smelter",
			"block vulcanizer",
			"block galvanic_bath",
			"block electric_heater",
			"block industrial_workbench",
			"block thermal_centrifuge",
			"block recycler",
			"block workstation",
			"block upgrade_table",
			"block block_breaker",
			"block pump",
			"block fluid_tank",
			"block fluid_tank_advanced",
			"block fluid_pipe",
			"block fluid_pipe_advanced",
			"block reinforced_fluid_pipe",
			"block steam_pipe",
			"block reinforced_steam_pipe",
			"block distillation_column",
			"block distillation_column_middle",
			"block distillation_column_top",
			"block rectification_section",
			"block oil",
			"block diesel",
			"block fuel_oil",
			"block fermenter",
			"block biofuel",
			"block nutrient_solution",
			"block oil_fire",
			"block soot_layer",
			"block item_pipe",
			"block item_pipe_advanced",
			"block battery_box",
			"block cesu",
			"block charge_pad",
			"block energy_condenser",
			"block iron_chest",
			"block storage_module",
			"block silver_chest",
			"block gold_chest",
			"block electrum_chest",
			"block shielding_chest",
			"block diamond_chest",
			"block smart_wire",
			"block monitor_core",
			"block monitor_panel",
			"block reactor_casing",
			"block reactor_glass",
			"block reactor_port",
			"block reactor_door",
			"block reactor_controller",
			"block reactor_lamp",
			"block reactor_button",
			"block fuel_rod_assembly",
			"block reactor_outlet",
			"block irradiated_soil",
			"block steam_nozzle",
			"block reactor_lever",
			"block garden_drone_station",
			"block incubator",
			"block incubator_dome",
			"block trellis",
			"block kok_sagyz",
			"block kok_sagyz_root",
			"block crystal_farm_floor",
			"block crystal_farm_glass",
			"block crystal_farm_door",
			"block crystal_farm_controller",
			"block crystal_seedbed",
			"block sprinkler",
			"block tin_ore",
			"block deepslate_tin_ore",
			"block silver_ore",
			"block deepslate_silver_ore",
			"block nickel_ore",
			"block deepslate_nickel_ore",
			"block sulfur_ore",
			"block deepslate_sulfur_ore",
			"block uranium_ore",
			"block deepslate_uranium_ore",
			"block palladium_ore",
			"block machine_casing",
			"block advanced_machine_casing",
			"block slag_block",
			"block carbon_ceramic",
			"block mob_repeller",
			"block mob_repeller_mv",
			"block mob_repeller_hv",
			"block tempered_iron_block",
			"block silver_plate_block",
			"block tempered_iron_plate_block",
			"block enriched_uranium_torch",
			"block enriched_uranium_wall_torch",
			"block engraved_plate_0",
			"block engraved_plate_1",
			"block engraved_plate_2",
			"block engraved_plate_3",
			"block engraved_plate_4",
			"block engraved_plate_5",
			"block engraved_plate_6",
			"block engraved_plate_7",
			"block engraved_plate_8",
			"block engraved_plate_9",
			"block broken_engraved_plate_w",
			"block broken_engraved_plate_k",
			"block broken_engraved_plate_p",
			"block broken_engraved_plate_b",
			"block broken_engraved_plate_d",
			"block broken_engraved_plate_r",
			"block broken_engraved_plate_m",
			"item generator",
			"item geothermal_generator",
			"item solar_panel",
			"item moonlit_solar_panel",
			"item daylight_solar_panel",
			"item radiant_solar_panel",
			"item concentrator_section",
			"item water_mill",
			"item wind_mill",
			"item high_altitude_wind_mill",
			"item storm_wind_mill",
			"item lightning_rod_generator",
			"item creative_energy_source",
			"item mob_wheel_controller",
			"item mob_wheel_frame",
			"item mob_wheel_rotor",
			"item mob_wheel_gate",
			"item piezo_plate",
			"item silent_piezo_plate",
			"item cable_breaker",
			"item copper_cable",
			"item tin_cable",
			"item gold_cable",
			"item electrum_cable",
			"item insulated_copper_cable",
			"item insulated_tin_cable",
			"item insulated_gold_cable",
			"item insulated_electrum_cable",
			"item macerator",
			"item teleporter",
			"item electric_furnace",
			"item extractor",
			"item compressor",
			"item component_repair_bench",
			"item canning_machine",
			"item sawmill",
			"item assembler",
			"item polymerizer",
			"item vulcanizer",
			"item alloy_smelter",
			"item galvanic_bath",
			"item thermal_centrifuge",
			"item electric_heater",
			"item iron_furnace",
			"item industrial_workbench",
			"item workstation",
			"item recycler",
			"item upgrade_table",
			"item block_breaker",
			"item vacuum_capsule",
			"item filled_vacuum_capsule",
			"item oil_bucket",
			"item diesel_bucket",
			"item fuel_oil_bucket",
			"item biofuel_bucket",
			"item nutrient_solution_bucket",
			"item fluid_pipe",
			"item fluid_pipe_advanced",
			"item reinforced_fluid_pipe",
			"item steam_pipe",
			"item reinforced_steam_pipe",
			"item distillation_column",
			"item rectification_section",
			"item fermenter",
			"item pump",
			"item fluid_tank",
			"item fluid_tank_advanced",
			"item stock_display_frame",
			"item item_pipe",
			"item item_pipe_advanced",
			"item battery_box",
			"item cesu",
			"item charge_pad",
			"item energy_condenser",
			"item iron_chest",
			"item storage_module",
			"item silver_chest",
			"item gold_chest",
			"item electrum_chest",
			"item shielding_chest",
			"item diamond_chest",
			"item oak_iron_chest_boat",
			"item spruce_iron_chest_boat",
			"item birch_iron_chest_boat",
			"item jungle_iron_chest_boat",
			"item acacia_iron_chest_boat",
			"item cherry_iron_chest_boat",
			"item dark_oak_iron_chest_boat",
			"item pale_oak_iron_chest_boat",
			"item mangrove_iron_chest_boat",
			"item bamboo_iron_chest_raft",
			"item oak_silver_chest_boat",
			"item spruce_silver_chest_boat",
			"item birch_silver_chest_boat",
			"item jungle_silver_chest_boat",
			"item acacia_silver_chest_boat",
			"item cherry_silver_chest_boat",
			"item dark_oak_silver_chest_boat",
			"item pale_oak_silver_chest_boat",
			"item mangrove_silver_chest_boat",
			"item bamboo_silver_chest_raft",
			"item oak_gold_chest_boat",
			"item spruce_gold_chest_boat",
			"item birch_gold_chest_boat",
			"item jungle_gold_chest_boat",
			"item acacia_gold_chest_boat",
			"item cherry_gold_chest_boat",
			"item dark_oak_gold_chest_boat",
			"item pale_oak_gold_chest_boat",
			"item mangrove_gold_chest_boat",
			"item bamboo_gold_chest_raft",
			"item oak_electrum_chest_boat",
			"item spruce_electrum_chest_boat",
			"item birch_electrum_chest_boat",
			"item jungle_electrum_chest_boat",
			"item acacia_electrum_chest_boat",
			"item cherry_electrum_chest_boat",
			"item dark_oak_electrum_chest_boat",
			"item pale_oak_electrum_chest_boat",
			"item mangrove_electrum_chest_boat",
			"item bamboo_electrum_chest_raft",
			"item oak_diamond_chest_boat",
			"item spruce_diamond_chest_boat",
			"item birch_diamond_chest_boat",
			"item jungle_diamond_chest_boat",
			"item acacia_diamond_chest_boat",
			"item cherry_diamond_chest_boat",
			"item dark_oak_diamond_chest_boat",
			"item pale_oak_diamond_chest_boat",
			"item mangrove_diamond_chest_boat",
			"item bamboo_diamond_chest_raft",
			"item oak_shielding_chest_boat",
			"item spruce_shielding_chest_boat",
			"item birch_shielding_chest_boat",
			"item jungle_shielding_chest_boat",
			"item acacia_shielding_chest_boat",
			"item cherry_shielding_chest_boat",
			"item dark_oak_shielding_chest_boat",
			"item pale_oak_shielding_chest_boat",
			"item mangrove_shielding_chest_boat",
			"item bamboo_shielding_chest_raft",
			"item smart_wire",
			"item monitor_core",
			"item monitor_panel",
			"item capacity_card",
			"item uranium_fuel_rod",
			"item empty_fuel_rod",
			"item depleted_uranium",
			"item reactor_casing",
			"item irradiated_soil",
			"item reactor_glass",
			"item reactor_port",
			"item reactor_door",
			"item reactor_controller",
			"item reactor_lamp",
			"item steam_nozzle",
			"item reactor_outlet",
			"item reactor_button",
			"item reactor_lever",
			"item fuel_rod_assembly",
			"item cotton_seeds",
			"item cotton_fiber",
			"item kok_sagyz_root",
			"item inulin",
			"item sprinkler",
			"item incubator",
			"item trellis",
			"item kok_sagyz_seeds",
			"item crystal_farm_floor",
			"item crystal_farm_glass",
			"item crystal_farm_door",
			"item crystal_farm_controller",
			"item crystal_seedbed",
			"item garden_drone_station",
			"item garden_drone",
			"item electronic_circuit",
			"item advanced_circuit",
			"item assembly_blueprint",
			"item copper_coil",
			"item spatial_crystal",
			"item resonance_coil",
			"item choke",
			"item choke_reinforced",
			"item choke_advanced",
			"item irradiated_slag",
			"item irradiated_diamond",
			"item resonant_shard",
			"item reinforced_amethyst",
			"item mutagen_dust",
			"item raw_rubber",
			"item oil_slime_spawn_egg",
			"item biomass",
			"item rubber",
			"item flux_thread",
			"item fluxweave_cloth",
			"item unstable_isotope",
			"item energy_clot_i",
			"item energy_clot_ii",
			"item energy_clot_iii",
			"item windmill_rotor",
			"item water_mill_wheel",
			"item windmill_rotor_reinforced",
			"item windmill_rotor_advanced",
			"item lightning_rod_conductor_tip",
			"item lightning_rod_conductor_tip_reinforced",
			"item lightning_rod_conductor_tip_advanced",
			"item water_mill_wheel_reinforced",
			"item water_mill_wheel_advanced",
			"item wooden_gear",
			"item stone_gear",
			"item iron_gear",
			"item gold_gear",
			"item silver_gear",
			"item electrum_gear",
			"item basic_bearing",
			"item reinforced_bearing",
			"item netherite_drill_head",
			"item core_barrel",
			"item drill_column_module",
			"item netherite_drill_upgrade_smithing_template",
			"item tempered_iron",
			"item iron_dust",
			"item copper_dust",
			"item gold_dust",
			"item coal_dust",
			"item diamond_dust",
			"item emerald_dust",
			"item empty_can",
			"item canned_ration",
			"item lapis_dust",
			"item tin_dust",
			"item raw_tin",
			"item tin_ingot",
			"item silver_dust",
			"item raw_silver",
			"item silver_ingot",
			"item nickel_dust",
			"item raw_nickel",
			"item nickel_ingot",
			"item bronze_ingot",
			"item invar_ingot",
			"item cupronickel_ingot",
			"item electrum_ingot",
			"item netherite_alloy_ingot",
			"item sulfur_dust",
			"item raw_sulfur",
			"item uranium_dust",
			"item raw_uranium",
			"item uranium_ingot",
			"item uranium_shavings",
			"item refined_uranium",
			"item shielding_alloy_ingot",
			"item shielding_alloy_plate",
			"item shielding_alloy_reinforced_plate",
			"item reactor_circuit",
			"item control_rod_drive",
			"item palladium_dust",
			"item raw_palladium",
			"item palladium_ingot",
			"item battery",
			"item energy_crystal_blank",
			"item energy_crystal",
			"item lapotron_crystal_blank",
			"item lapotron_crystal",
			"item resonant_crystal_blank",
			"item resonant_crystal",
			"item copper_plate",
			"item gold_plate",
			"item iron_plate",
			"item tin_plate",
			"item silver_plate",
			"item nickel_plate",
			"item uranium_plate",
			"item palladium_plate",
			"item tempered_iron_plate",
			"item bronze_plate",
			"item invar_plate",
			"item cupronickel_plate",
			"item electrum_plate",
			"item bronze_reinforced_plate",
			"item invar_reinforced_plate",
			"item cupronickel_reinforced_plate",
			"item electrum_reinforced_plate",
			"item tin_ore",
			"item deepslate_tin_ore",
			"item silver_ore",
			"item deepslate_silver_ore",
			"item nickel_ore",
			"item deepslate_nickel_ore",
			"item sulfur_ore",
			"item deepslate_sulfur_ore",
			"item uranium_ore",
			"item deepslate_uranium_ore",
			"item palladium_ore",
			"item machine_casing",
			"item advanced_machine_casing",
			"item slag_block",
			"item slag_poor",
			"item slag",
			"item slag_rich",
			"item ash",
			"item recycler_blades_iron",
			"item recycler_blades_tempered",
			"item recycler_blades_diamond",
			"item carbon_ceramic",
			"item carbon_rod",
			"item carbon_rod_double",
			"item carbon_briquette",
			"item ceramic_plate",
			"item soot",
			"item rtp_chip",
			"item alignment_chip_day",
			"item alignment_chip_night",
			"item resonance_chip",
			"item empty_chip",
			"item mutation_chip_transform",
			"item mutation_chip_duplicate",
			"item mutation_chip_create",
			"item mute_chip",
			"item stats_chip",
			"item soul_vessel",
			"item overclocker_chip_i",
			"item overclocker_chip_ii",
			"item overclocker_chip_iii",
			"item tempered_iron_pickaxe",
			"item tempered_iron_axe",
			"item tempered_iron_hoe",
			"item tempered_iron_shovel",
			"item tempered_iron_sword",
			"item tempered_iron_helmet",
			"item tempered_iron_chestplate",
			"item tempered_iron_leggings",
			"item tempered_iron_boots",
			"item fluxweave_helmet",
			"item fluxweave_chestplate",
			"item fluxweave_leggings",
			"item fluxweave_boots",
			"item shielding_helmet",
			"item shielding_chestplate",
			"item shielding_leggings",
			"item shielding_boots",
			"item insulated_helmet",
			"item insulated_chestplate",
			"item insulated_leggings",
			"item insulated_boots",
			"item network_analyzer",
			"item wind_gauge",
			"item geiger_counter",
			"item wrench",
			"item guide_book",
			"item teleporter_remote",
			"item battery_pouch",
			"item shielding_pouch",
			"item energy_pack",
			"item electric_drill",
			"item electric_drill_diamond_tip",
			"item electric_drill_netherite_tip",
			"item electric_chainsaw",
			"item electric_chainsaw_diamond_tip",
			"item electric_shovel",
			"item electric_shovel_diamond_tip",
			"item electric_hoe",
			"item electric_hoe_diamond_tip",
			"item electric_saber",
			"item electric_bow",
			"item electromagnet",
			"item electromagnet_advanced",
			"item module_blank",
			"item magnet_filter_module",
			"item jetpack",
			"item scythe_wood",
			"item scythe_stone",
			"item scythe_copper",
			"item scythe_iron",
			"item scythe_gold",
			"item scythe_tempered_iron",
			"item scythe_diamond",
			"item scythe_netherite",
			"item forge_hammer",
			"item mob_repeller",
			"item mob_repeller_mv",
			"item mob_repeller_hv",
			"item tempered_iron_block",
			"item silver_plate_block",
			"item tempered_iron_plate_block",
			"item enriched_uranium_torch",
			"item engraved_plate_0",
			"item engraved_plate_1",
			"item engraved_plate_2",
			"item engraved_plate_3",
			"item engraved_plate_4",
			"item engraved_plate_5",
			"item engraved_plate_6",
			"item engraved_plate_7",
			"item engraved_plate_8",
			"item engraved_plate_9",
			"item broken_engraved_plate_w",
			"item broken_engraved_plate_k",
			"item broken_engraved_plate_p",
			"item broken_engraved_plate_b",
			"item broken_engraved_plate_d",
			"item broken_engraved_plate_r",
			"item broken_engraved_plate_m",
			"block_entity generator: generator",
			"block_entity geothermal_generator: geothermal_generator",
			"block_entity solar_panel: solar_panel",
			"block_entity moonlit_solar_panel: moonlit_solar_panel",
			"block_entity daylight_solar_panel: daylight_solar_panel",
			"block_entity radiant_solar_panel: radiant_solar_panel",
			"block_entity water_mill: water_mill",
			"block_entity wind_mill: wind_mill",
			"block_entity high_altitude_wind_mill: high_altitude_wind_mill",
			"block_entity storm_wind_mill: storm_wind_mill",
			"block_entity lightning_rod_generator: lightning_rod_generator",
			"block_entity creative_energy_source: creative_energy_source",
			"block_entity mob_wheel_controller: mob_wheel_controller",
			"block_entity piezo_plate: piezo_plate silent_piezo_plate",
			"block_entity copper_cable: copper_cable tin_cable gold_cable electrum_cable insulated_copper_cable insulated_tin_cable insulated_gold_cable insulated_electrum_cable",
			"block_entity macerator: macerator",
			"block_entity component_repair_bench: component_repair_bench",
			"block_entity upgrade_table: upgrade_table",
			"block_entity teleporter: teleporter",
			"block_entity electric_furnace: electric_furnace",
			"block_entity iron_furnace: iron_furnace",
			"block_entity extractor: extractor",
			"block_entity compressor: compressor",
			"block_entity recycler: recycler",
			"block_entity canning_machine: canning_machine",
			"block_entity sawmill: sawmill",
			"block_entity assembler: assembler",
			"block_entity polymerizer: polymerizer",
			"block_entity vulcanizer: vulcanizer",
			"block_entity alloy_smelter: alloy_smelter",
			"block_entity galvanic_bath: galvanic_bath",
			"block_entity electric_heater: electric_heater",
			"block_entity thermal_centrifuge: thermal_centrifuge",
			"block_entity workstation: workstation",
			"block_entity industrial_workbench: industrial_workbench",
			"block_entity block_breaker: block_breaker",
			"block_entity fluid_pipe: fluid_pipe fluid_pipe_advanced reinforced_fluid_pipe steam_pipe reinforced_steam_pipe",
			"block_entity distillation_column: distillation_column",
			"block_entity distillation_column_segment: distillation_column_middle distillation_column_top",
			"block_entity pump: pump",
			"block_entity fluid_tank: fluid_tank fluid_tank_advanced",
			"block_entity fermenter: fermenter",
			"block_entity item_pipe: item_pipe item_pipe_advanced",
			"block_entity smart_wire: smart_wire",
			"block_entity monitor_core: monitor_core",
			"block_entity monitor_panel: monitor_panel",
			"block_entity battery_box: battery_box",
			"block_entity cesu: cesu",
			"block_entity charge_pad: charge_pad",
			"block_entity energy_condenser: energy_condenser",
			"block_entity iron_chest: iron_chest",
			"block_entity storage_module: storage_module",
			"block_entity silver_chest: silver_chest",
			"block_entity gold_chest: gold_chest",
			"block_entity electrum_chest: electrum_chest",
			"block_entity diamond_chest: diamond_chest",
			"block_entity shielding_chest: shielding_chest",
			"block_entity reactor_controller: reactor_controller",
			"block_entity fuel_rod_assembly: fuel_rod_assembly",
			"block_entity reactor_port: reactor_port",
			"block_entity steam_nozzle: steam_nozzle",
			"block_entity reactor_outlet: reactor_outlet",
			"block_entity reactor_door: reactor_door",
			"block_entity kok_sagyz_root: kok_sagyz_root",
			"block_entity incubator: incubator",
			"block_entity garden_drone_station: garden_drone_station",
			"block_entity crystal_farm_controller: crystal_farm_controller",
			"block_entity sprinkler: sprinkler",
			"block_entity mob_repeller: mob_repeller",
			"block_entity mob_repeller_mv: mob_repeller_mv",
			"block_entity mob_repeller_hv: mob_repeller_hv",
			"menu generator",
			"menu solar_panel",
			"menu moonlit_solar_panel",
			"menu daylight_solar_panel",
			"menu radiant_solar_panel",
			"menu geothermal_generator",
			"menu water_mill",
			"menu wind_mill",
			"menu high_altitude_wind_mill",
			"menu storm_wind_mill",
			"menu lightning_rod_generator",
			"menu creative_energy_source",
			"menu mob_wheel_controller",
			"menu macerator",
			"menu electric_furnace",
			"menu extractor",
			"menu compressor",
			"menu recycler",
			"menu component_repair_bench",
			"menu upgrade_table",
			"menu canning_machine",
			"menu sawmill",
			"menu assembler",
			"menu polymerizer",
			"menu vulcanizer",
			"menu electric_heater",
			"menu alloy_smelter",
			"menu galvanic_bath",
			"menu teleporter_station",
			"menu thermal_centrifuge",
			"menu block_breaker",
			"menu distillation_column",
			"menu fermenter",
			"menu pump",
			"menu battery_box",
			"menu energy_condenser",
			"menu cesu",
			"menu charge_pad",
			"menu iron_chest",
			"menu storage_module_3",
			"menu storage_module_6",
			"menu silver_chest",
			"menu gold_chest",
			"menu electrum_chest",
			"menu diamond_chest",
			"menu shielding_chest",
			"menu double_chest",
			"menu monitor_core",
			"menu reactor_controller",
			"menu incubator",
			"menu sprinkler",
			"menu garden_drone_station",
			"menu teleporter_remote",
			"menu magnet",
			"menu mob_repeller",
			"menu mob_repeller_mv",
			"menu mob_repeller_hv");
}
