package dev.alaindustrial.command.demo;

import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.decoration.GlowItemFrame;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Block;

/**
 * Zone <b>showcase</b> (MOD-294, wall at the back edge z=50, frames at z=49): EVERY item of the registry in a
 * glow item frame — block items included since MOD-586, so the wall is the mod's index rather
 * than a leftovers shelf. The frames are generated by looping {@code BuiltInRegistries.ITEM}, so
 * the wall refills itself whenever the registry grows — and the item-coverage gametest reddens
 * the day the registry outgrows the wall. The wall is the very last row of the stand: there is nothing
 * behind it (MOD-659 — the item-pipe row that used to stand there was invisible from the front).
 *
 * <p>Frames are entities: {@code DemoStand#killLooseEntities} discards them on every rebuild and this
 * method places them anew after the wall, which keeps rebuild×2 idempotent. Glow frames render
 * their item readable in the dark without emitting light. The wall itself is floor blocks — a
 * support that is part of the stand's own block pass, so a frame never hangs on terrain the
 * stand does not own.
 *
 * <p>Domain (coding standard, section 1): cross-cutting view (every item of the registry); the
 * exhibits belong to the domains of their own blocks.
 */
final class ShowcaseZone implements DemoZone {
	private static final Block FLOOR = StandLayout.FLOOR;

	/** Camera of {@code /ala demo tp showcase}. */
	static final DemoStand.TpPoint SHOWCASE_CAMERA =
			new DemoStand.TpPoint("showcase", 43.0, 5.0, 41.0, 0.0f, 8.0f, false);

	/** Camera of {@code /ala demo tp showcase_west}. */
	static final DemoStand.TpPoint SHOWCASE_WEST_CAMERA =
			new DemoStand.TpPoint("showcase_west", 15.0, 5.0, 41.0, 0.0f, 8.0f, false);

	/** Camera of {@code /ala demo tp showcase_east}. */
	static final DemoStand.TpPoint SHOWCASE_EAST_CAMERA =
			new DemoStand.TpPoint("showcase_east", 71.0, 5.0, 41.0, 0.0f, 8.0f, false);

	/**
	 * Showcase wall (MOD-294): the LAST row of the stand, columns x=1..{@link #SHOWCASE_COLUMNS}. The
	 * frames hang on its front (north) face, one row in front of it — so the wall closes the stand and
	 * there is no cell behind it (MOD-659: the old item-pipe row stood there, invisible from the front).
	 */
	private static final int SHOWCASE_WALL_Z = DemoStand.DEPTH - 1;
	private static final int SHOWCASE_COLUMNS = DemoStand.WIDTH - 2;
	/** The wall's bottom row. y=1 is the first cell above the floor. */
	private static final int SHOWCASE_BASE_Y = 1;
	/**
	 * Six rows: every frame within arm's reach without craning, and the wall spans the whole stand
	 * instead of towering over a corner of it (MOD-659; it used to be nine rows of forty).
	 *
	 * <p>The wall shows EVERY item of the mod since MOD-586, block items included. Capacity is a
	 * deadline, not a preference: the wall fills from the registry, and the day the registry outgrows
	 * it the coverage gametest reddens in whatever task happened to add the item. The current item
	 * count is read from the registry, never restated here; six rows of {@code WIDTH - 2} are 492 slots.
	 */
	private static final int SHOWCASE_ROWS = 6;

	@Override
	public void build(StandWriter w) {
		ServerLevel level = w.level();
		BlockPos origin = w.origin();
		for (int row = 0; row < SHOWCASE_ROWS; row++) {
			for (int x = 1; x <= SHOWCASE_COLUMNS; x++) {
				w.set(x, SHOWCASE_BASE_Y + row, SHOWCASE_WALL_Z, FLOOR);
			}
		}
		List<Item> items = DemoStand.showcaseItems();
		int placed = 0;
		for (int row = 0; row < SHOWCASE_ROWS && placed < items.size(); row++) {
			for (int x = 1; x <= SHOWCASE_COLUMNS && placed < items.size(); x++) {
				GlowItemFrame frame = new GlowItemFrame(level,
						origin.offset(x, SHOWCASE_BASE_Y + row, SHOWCASE_WALL_Z - 1),
						Direction.NORTH);
				frame.setItem(new ItemStack(items.get(placed++)));
				level.addFreshEntity(frame);
			}
		}
	}
}
