package dev.alaindustrial.client.guide;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import dev.alaindustrial.Industrialization;
import java.io.Reader;
import java.util.List;
import java.util.Optional;
import net.minecraft.client.Minecraft;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.resources.Resource;

/**
 * Loads the baked Guide Book content (MOD-067) for the client's language from
 * {@code assets/alaindustrial/guide_book/<locale>.json} (generated by {@code docs/tools/gen_guide_book.py}),
 * falling back to {@code en_us}, then to an empty book. Plain POJOs parsed with Gson — the JSON is a
 * self-contained per-locale tree {@code Book -> Tab -> Entry -> Page[]}.
 */
public final class GuideContent {
	private static final Gson GSON = new Gson();

	public static final class Book {
		public String locale = "en_us";
		public int version = 1;
		public List<Tab> tabs = List.of();
	}

	public static final class Tab {
		public String id = "";
		public String title = "";
		public String icon = "";
		public List<Entry> entries = List.of();
	}

	public static final class Entry {
		public String id = "";
		public String title = "";
		public String icon = "";
		@SerializedName("block_id")
		public String blockId = "";
		public List<Page> pages = List.of();
	}

	public static final class Page {
		public String type = "text";
		public String title = "";
		public String text = "";
		public List<String> lines = List.of();  // pre-formatted, localized stat lines
		// Recipe pages: a baked 3×3 grid of item ids (9 cells, "" = empty), the result and its count.
		public List<String> grid = List.of();
		@SerializedName("recipe_type")
		public String recipeType = "";
		@SerializedName("result_id")
		public String resultId = "";
		@SerializedName("result_count")
		public int resultCount = 1;
		// Cycling recipe alternatives (e.g. the eight scythe tiers, or a from-scratch vs upgrade craft).
		// When present with more than one entry, the recipe view rotates through them once per second;
		// the single-recipe fields above stay filled with the first variant for back-compat.
		public List<RecipeVariant> variants = List.of();
	}

	/** One alternative in a cycling recipe page (see {@link Page#variants}). */
	public static final class RecipeVariant {
		public List<String> grid = List.of();
		@SerializedName("recipe_type")
		public String recipeType = "";
		@SerializedName("result_id")
		public String resultId = "";
		@SerializedName("result_count")
		public int resultCount = 1;
	}

	private GuideContent() {
	}

	/** Load the book for the current client language, falling back to en_us, then an empty book. */
	public static Book load() {
		Minecraft mc = Minecraft.getInstance();
		String locale = mc.options.languageCode;
		Book book = tryLoad(mc, locale);
		if (book == null && !"en_us".equals(locale)) {
			book = tryLoad(mc, "en_us");
		}
		return book != null ? book : new Book();
	}

	private static Book tryLoad(Minecraft mc, String locale) {
		Identifier id = Industrialization.id("guide_book/" + locale + ".json");
		Optional<Resource> res = mc.getResourceManager().getResource(id);
		if (res.isEmpty()) {
			return null;
		}
		try (Reader reader = res.get().openAsReader()) {
			Book book = GSON.fromJson(reader, Book.class);
			return (book != null && book.tabs != null) ? book : null;
		} catch (Exception e) {
			Industrialization.LOGGER.error("Failed to load guide book {}: {}", id, e.toString());
			return null;
		}
	}
}
